### ISSUE TITLE
界面缩放功能

### ISSUE THREAD

**Issue by HelloWRC** [ClassIsland/ClassIsland#1]
提供界面缩放功能，使主界面可以调整缩放比例大小

**Comment by LiuYan-xwx** [comment]
@classisland-bot /ping

**Comment by undefftr** [comment]
@classisland-bot /ping

**Comment by DryIce-cc** [comment]
@classisland-bot /ping

**Comment by HelloWRC** [comment]
@classisland-bot /ping

**Comment by undefftr** [comment]
#1是真满了（

**Comment by DryIce-cc** [comment]
@classisland-bot /ping /ping /pong /pong

**Comment by DryIce-cc** [comment]
@all-contributors please add @LyRin-owo for promotion
