### ISSUE TITLE
[功能请求]: 在课表右侧新增当前时间的显示

### ISSUE THREAD

**Issue by Misaka2298** [ClassIsland/ClassIsland#104]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

如题，班里许多同学都很需要这个功能，因为伸头去看班级墙上并不是很准的传统时钟实在是太麻烦了
当然，也可以用Digital Clock等第三方桌面时钟软件来实现，但跟直接集成在课表里面比起来还是没那么美观xd

### 想要实现或优化的功能

在课表右侧新增一个时钟，设置里有开关，同时在设置里可以自定义时间格式，如“HH:mm:ss” “hh:mm” “HH:mm”等

**Comment by HelloWRC** [comment]
感谢您的建议。这个功能我打算在1.5和 https://github.com/HelloWRC/ClassIsland/issues/98 一起实现，并将这个功能作为一个快速信息组件加入。

**Comment by HelloWRC** [comment]
已在dev实现。
