### ISSUE TITLE
[功能请求]: 倒计时始终精确到秒

### ISSUE THREAD

**Issue by DryIce-cc** [ClassIsland/ClassIsland#115]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

喜欢 ECS 样式的倒计时，简洁直观。

### 想要实现或优化的功能

课程和课间倒计时始终显示 (时 :)分 : 秒，样式和 ECS 类似。
![a](https://github.com/HelloWRC/ClassIsland/assets/165131008/508720d6-b350-4564-bc21-f315e219402c)

**Comment by HelloWRC** [comment]
感谢您的建议。

**Comment by DryIce-cc** [comment]
时钟组件已支持显示到秒，此请求不再必要。

**Comment by DryIce-cc** [comment]
已向 dev 提交 Pull Request。
