### ISSUE TITLE
[功能请求]: 在上课时仅显示当前课程进度选项

### ISSUE THREAD

**Issue by DaJiChi** [ClassIsland/ClassIsland#122]
### 检查清单

- [x] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

在上课时，学生与老师有需求需要观看当前课程剩余时间。
现有功能仅能提供在【“前台是最大化窗口时”/“前台时全屏窗口时”/上课时】隐藏全部界面，而没有【仅显示当前课程进度】的选项。

### 想要实现或优化的功能

希望能够在【应用设置->基本->隐藏窗口】中新增【仅显示当前课程进度】选项。
且在上课时【仅显示当前课程的进度】，【隐藏】其他课程。
实现效果如图：
![QQ截图20240514234207](https://github.com/HelloWRC/ClassIsland/assets/61936948/105e2285-892b-4c2e-8dee-b88a105965f5)

**Comment by HelloWRC** [comment]
感谢您的建议。

**Comment by HelloWRC** [comment]
已在 f0c82bccf9e31dad1d554bc41191a786a08fbb8d 实现。
