### ISSUE TITLE
[Bug]: 临时层不自动删除

### ISSUE THREAD

**Issue by yang932** [ClassIsland/ClassIsland#135]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

1.创建一个临时层并在一天的正常使用后正常关机
2.第二日开机时会发现原临时层未自动删除（疑似在#75修复后出现？）

### 期望的行为

第二天启动时与过去版本一样临时层自动删除

### 实际结果

临时层未自动删除

### 应用版本

1.3.4.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
这个问题已经在1.4.0.0修复，请更新到正式版后再试试看。

**Comment by DryIce-cc** [comment]
最新测试版，没有修复。 
第二日开机，原临时层未自动删除。

另，如果未关机（如休眠），第二日会显示上一天临时层，
第一节课下课时 ClassIsland 会全自动重启，并切换为当日课表。
@HelloWRC

**Comment by HelloWRC** [comment]
> 最新测试版，没有修复。 第二日开机，原临时层未自动删除。
> 
> 另，如果未关机（如休眠），第二日会显示上一天临时层， 第一节课下课时 ClassIsland 会全自动重启，并切换为当日课表。 @HelloWRC

这个问题是在电脑不关机连夜运行出现的吗，还是在正常关机并重启ClassIsland后也会出现？

**Comment by DryIce-cc** [comment]
> > 最新测试版，没有修复。 第二日开机，原临时层未自动删除。
> > 另，如果未关机（如休眠），第二日会显示上一天临时层， 第一节课下课时 ClassIsland 会全自动重启，并切换为当日课表。 @HelloWRC
> 
> 这个问题是在电脑不关机连夜运行出现的吗，还是在正常关机并重启 ClassIsland 后也会出现？

“第二日开机，原临时层未自动删除。”是在正常关机并重启 ClassIsland 后会出现的。

**Comment by HelloWRC** [comment]
已修复。
