### ISSUE TITLE
[Bug]: 天气预警显示时间错误

### ISSUE THREAD

**Issue by hello8693DSZ** [ClassIsland/ClassIsland#138]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

启用天气预警。

### 期望的行为

下课后播报预警

### 实际结果

下课不播报，一上课就发出提醒开始播报。

### 应用版本

截止到现在的测试版本最新版

### 操作系统版本

学校断网了，改天补充，win10 22h2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by LiuYan-xwx** [comment]
你需要在`课间休息`时间段设置天气预警显示，而不是上课，天气预警会在时间段开始时提醒
