### ISSUE TITLE
[功能请求]: 天气预警关键词过滤

### ISSUE THREAD

**Issue by hello8693DSZ** [ClassIsland/ClassIsland#139]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

本地由于沿海，气象台经常发布海上预警，希望增加关键词过滤以屏蔽海上相关预警。

### 想要实现或优化的功能

一个界面用于设置过滤词

**Comment by Qsgz2023ji5ban** [comment]
复议。
我们内陆地区还经常海上预警呢。

**Comment by HelloWRC** [comment]
已实现。
