### ISSUE TITLE
[Bug]:档案文件因某些因素写入失败后导致档案文件被清空

### ISSUE THREAD

**Issue by Doctor-yoi** [ClassIsland/ClassIsland#150]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

编辑档案时点击保存后立即使用任务管理器中止进程（某些情况下不档案课表正常关机也会导致该现象）
再次启动软件后会报错且档案消失（无法恢复）

### 期望的行为

保存档案前先进行备份，如保存成功则删除备份
启动时读取档案出错则尝试读取备份，如均未读取成功则自动初始化新的档案后再次读取

### 实际结果

保存档案时未备份导致写入文件失败时档案被清空

### 应用版本

v1.4.0.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Doctor-yoi** [comment]
初步探查怀疑是File.WriteAllText的锅。File.WriteAllText会首先清空文件内容后再写入，如在清空文件内容后因某些因素导致没有写入就会导致档案出现不可逆的损坏，并导致下一次启动时出现异常

**Comment by HelloWRC** [comment]
已修复。
