### ISSUE TITLE
[Bug]: 加载临时课表后改变课表信息会使临时课表失效

### ISSUE THREAD

**Issue by yang932** [ClassIsland/ClassIsland#154]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

1.加载一个临时课表
2.在档案编辑界面点击该课表的“课表信息”

### 期望的行为

临时课表不会失效

### 实际结果

临时课表在点击课表信息后立即失效，需重新设置

### 应用版本

1.4.0.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
已修复。
