### ISSUE TITLE
[Bug]: 在windows桌面被识别成全屏窗口误隐藏

### ISSUE THREAD

**Issue by LiuYan-xwx** [ClassIsland/ClassIsland#158]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

在1.4版本及以前没有出现过这个问题，升级1.4.1后出现。

1. 确认版本为1.4.1
2. 打开设置里的全屏时隐藏窗口
3. 回到桌面点几下

### 期望的行为

主界面因为全屏隐藏设置被隐藏

### 实际结果

主界面正常显示

### 堆栈跟踪（可选）

```shell
桌面没有其他窗口，然而相同环境一换到1.4.0.0就正常
```

### 应用版本

1.4.0.1

### 操作系统版本

Windows11 23H2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
已修复。
