### ISSUE TITLE
[Bug]: 自动更新为1.4.0.1时无法启动程序

### ISSUE THREAD

**Issue by gaopx11233** [ClassIsland/ClassIsland#160]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

1.找到一个1.4.0.1以下版本的客户端 2.自动更新

### 期望的行为

自动更新后打开软件

### 实际结果

未自动替换exe文件，手动打开EXE后显示准备更新，之后界面消失，软件无法运行，手动替换后可正常使用

### 应用版本

1.4.0.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
这个问题是由更新文件下载损坏导致的，目前已经在1.4.0.1添加了更新校验机制（#131）来防止这种情况。在从1.4.0.1升级时，应用会检查更新完整性。
