### ISSUE TITLE
[功能请求]: 对于课表三周轮换的支持

### ISSUE THREAD

**Issue by RainyHallways** [ClassIsland/ClassIsland#162]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

周六课表为三周轮换，但此项目只两周轮换

### 想要实现或优化的功能

为两周轮换拓展出三周轮换的功能

**Comment by DryIce-cc** [comment]
占个位，尝试一下实现独立的任意周数轮换（）

**Comment by DryIce-cc** [comment]
已实现！支持最多四周（实际无限）的独立轮换

**Comment by DryIce-cc** [comment]
在 Class Widgets 有镜像 issue：
- RinLit-233-shiroko/Class-Widgets#118
