### ISSUE TITLE
[Bug]: 打开“外观”设置有时会导致设置直接死机

### ISSUE THREAD

**Issue by wjj-8283** [ClassIsland/ClassIsland#172]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

打开软件设置，然后点击“外观”

### 期望的行为

正常加载设置的“外观”选项卡

### 实际结果

有概率会卡死或无法加载，卡死后关闭设置再打开会出现白色的空白窗口

### 应用版本

1.4.11-Griseo-24372c1

### 操作系统版本

10.0.26100.863，Windows 11 企业版LTSC

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by wjj-8283** [comment]
日志里面没有任何报错记录……

**Comment by HelloWRC** [comment]
这个问题我在调试时也遇到过，考虑可能是与 #92 相似的问题。尽管这个问题目前已经被部分解决了，但还是有些副作用，比如在这里提到的在比较复杂的页面（如外观页面）会直接冻结的问题。很遗憾，这个问题在我的能力范围内还没有比较好的解决方案，您可以考虑重启应用来缓解这个问题。

**Comment by wjj-8283** [comment]
好的好的，谢谢
重启应用后确实会恢复正常

**Comment by wjj-8283** [comment]
> 这个问题我在调试时也遇到过，考虑可能是与 #92 相似的问题。尽管这个问题目前已经被部分解决了，但还是有些副作用，比如在这里提到的在比较复杂的页面（如外观页面）会直接冻结的问题。很遗憾，这个问题在我的能力范围内还没有比较好的解决方案，您可以考虑重启应用来缓解这个问题。

那么能不能在任务栏图标的右键菜单中加入“重新启动”的选项，便于以后遇到问题时能够快速重启？

**Comment by jiangyin14** [comment]
推荐在双击打开ClassIsland提示“已有实例”的窗口加入一个“关闭已有实例，并开启新实例”的选项（按钮）

**Comment by HelloWRC** [comment]
> > 这个问题我在调试时也遇到过，考虑可能是与 #92 相似的问题。尽管这个问题目前已经被部分解决了，但还是有些副作用，比如在这里提到的在比较复杂的页面（如外观页面）会直接冻结的问题。很遗憾，这个问题在我的能力范围内还没有比较好的解决方案，您可以考虑重启应用来缓解这个问题。
> 
> 那么能不能在任务栏图标的右键菜单中加入“重新启动”的选项，便于以后遇到问题时能够快速重启？

已实现。

**Comment by wjj-8283** [comment]
你说迁移到Avalonia能不能根治这个问题？

**Comment by wjj-8283** [comment]
其实并没有完全修复啦，WRC只是缓解了相关问题，如果我在一瞬间打开大量的软件（比如我打开VSCode后再打开Github然后再切换到VSCode，或者用教室电脑打MC），导致资源长时间过度占用，界面还是照常冻结
