### ISSUE TITLE
[Bug]: 较长预警信息显示速度过快

### ISSUE THREAD

**Issue by Qsgz2023ji5ban** [ClassIsland/ClassIsland#173]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

在显示预警信息时速度过快

> 预警信息这么长，30秒一次？
> 

### 期望的行为

根据文字长度计算单次显示时间

### 实际结果

和30秒极速广告一样

### 应用版本

1.4.1.1

### 操作系统版本

LTSB 2016

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Qsgz2023ji5ban** [comment]
![无标题](https://github.com/ClassIsland/ClassIsland/assets/161912673/f4264a2b-fded-4bf9-8d42-cf69981166a0)

**Comment by HelloWRC** [comment]
已修复。
