### ISSUE TITLE
[Bug]: 「置底」的主界面与桌面图标共同闪动

### ISSUE THREAD

**Issue by KaguReion** [ClassIsland/ClassIsland#174]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

在教室电脑上（笔记本，双显卡）启动 ClassIsland，主界面出现后开始不规律闪动，偶尔伴随桌面图标共同闪动。

若此时用鼠标快速点击桌面，则闪动停止。当「上课」「下课」「天气预警」等提醒出现时，闪动停止。

这种闪动会导致开始菜单打开速度变慢。

*二次编辑* 当主窗口「置底」时复现了此问题。「置顶」时并未复现出该问题。

### 期望的行为

主界面和桌面图标不应当闪动。

### 实际结果

主界面和桌面图标闪动。

### 堆栈跟踪（可选）

```shell
并未出现任何崩溃提示，日志中无可参考信息。
```

### 应用版本

1.4.0.3-Firefly-10baa19(HEAD) (Core 1.4.0.0)

### 操作系统版本

Windows 11 22H2（具体系统版本下午在此更新，现在无法访问电脑）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Qsgz2023ji5ban** [comment]
在LTSB 2016上复现同样问题

**Comment by Qsgz2023ji5ban** [comment]
我们三台闪动的都是Microsoft Windows 10.0.14393（LTSB 2016）
从1.4.1.1-Griseo-24372c1(HEAD) (Core 1.4.0.0)到1.4.0.2-Firefly均有bug

**Comment by Qsgz2023ji5ban** [comment]
以下是这台机子的录像（重启文件资源管理器有概率解决）：
[OneDrive 文件共享](https://4wb5rx-my.sharepoint.com/:v:/g/personal/qsgz2023ji5ban_edicdn_eu_org/ERcw5rBG28lOn2HgkqE7J7QB8SLnRmYu15JQrgkJih7GeQ?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=c5uKC0)

**Comment by Qsgz2023ji5ban** [comment]
难道跟`explorer.exe`有关系？
@KaguReion 用Dism++关闭`在单独的进程中打开文件夹窗口`

**Comment by Qsgz2023ji5ban** [comment]
不行再打开

**Comment by jiangyin14** [comment]
多半跟cswin32重构native有关（）

**Comment by KaguReion** [comment]
> 难道跟`explorer.exe`有关系？ @KaguReion 用Dism++关闭`在单独的进程中打开文件夹窗口` 如图： ![无标题](https://private-user-images.githubusercontent.com/161912673/341330407-ce133aad-8655-4d53-b57f-2f13b4ecd4ea.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg5Njk1NTgsIm5iZiI6MTcxODk2OTI1OCwicGF0aCI6Ii8xNjE5MTI2NzMvMzQxMzMwNDA3LWNlMTMzYWFkLTg2NTUtNGQ1My1iNTdmLTJmMTNiNGVjZDRlYS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYyMVQxMTI3MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04ZTAzZWU5M2RlYmFkY2ZiNGZmZDNlYWZjNzk4MTI0NTFhOGZiMDg3YjhhYjJiN2I5Mjk3NjhiM2EyMjcxNTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5dWm2Y3kXm9VjXJizSM4-3gB8DxwVidh5eg3crlAEJA)

🤔还有这种操作？

感谢回复。不过本人这几天放假，无法接触到学校电脑，家里的电脑不能复现此问题，过几天回学校了试试看（

**Comment by HelloWRC** [comment]
已修复。
