### ISSUE TITLE
[Bug]: 更改显示器后，在应用设置中刷新显示器列表或切换显示器，导致应用崩溃

### ISSUE THREAD

**Issue by KaguReion** [ClassIsland/ClassIsland#175]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

为了复现该 bug，电脑上应已经连接两个或更多显示器；并且这些显示器应当直接连接到电脑，而不是通过集线器等设备分配的形式连接。可在 Windows 设置 > 系统 > 屏幕 中看到多个显示器。

![电脑上已连接多个显示器](https://github.com/ClassIsland/ClassIsland/assets/141834038/e866a8ba-c1ac-42c6-b4fb-4ac02ed22a2e)

1. 删除 ClassIsland 的 `Settings.json` 并启动，ClassIsland 进入引导界面，一切正常。打开 应用设置 > 窗口，在 显示器 下可以看到所有显示器，并可以自由选择主界面的显示位置。

![ClassIsland 可识别多显示器](https://github.com/ClassIsland/ClassIsland/assets/141834038/193089f4-d9cc-4388-963f-a0af264ad481)

2. 进行**任何**与多显示器设置相关的操作，**包括但不限于** 使用 Win+P 切换投影类型（复制、扩展），断开任一显示器或者连接先前的或新的显示器等。

![进行多显示器操作，这里以切换投影类型为例](https://github.com/ClassIsland/ClassIsland/assets/141834038/c2a26311-df98-4df0-8f71-ada86434bb34)

3. 上一步完成后，打开 应用设置 > 窗口，刷新显示器列表或者在 显示器 下重新选择任一显示器，软件即刻崩溃，弹出数百个错误窗口，但软件的主界面仍然在更新。在数十秒后，错误窗口停止弹出，所有 ClassIsland 窗口全部卡死，主界面停止更新，又在数十秒后所有窗口统一关闭。在卡死到关闭期间，无法通过 taskkill 或 关闭所有窗口 的方式关闭 ClassIsland。

![软件崩溃并弹出报错窗口](https://github.com/ClassIsland/ClassIsland/assets/141834038/3c3c7bc2-7b5b-4cac-b1c3-387a6b3d1b0f)

4. **无论是否恢复到先前的多显示器设置**，**也无论是否将 `Settings.json.bak` 覆盖到 `Settings.json`**，重新打开 ClassIsland 后，在打开界面继续报错。（此时 ClassIsland 主题色并非来源于桌面取色）删除 `Settings.json` 后，ClassIsland 恢复正常并重新进入引导页面。

![重新打开 ClassIsland 时仍然崩溃](https://github.com/ClassIsland/ClassIsland/assets/141834038/591603cf-6db2-4472-bf09-1d6fe5b62f08)

![平铺展示报错窗口](https://github.com/ClassIsland/ClassIsland/assets/141834038/8032f8c9-8010-46b0-a868-f77207282cf9)

### 期望的行为

不应当因为多显示器操作的切换而导致软件崩溃。

### 实际结果

进行多显示器操作后软件崩溃，`Settings.json` 和 `Settings.json.bak` 中，变量 `WindowDockingMonitorIndex` 变为 `-1`。

### 堆栈跟踪（可选）

```shell
System.IndexOutOfRangeException: Index was outside the bounds of the array.
    at ClassIsland.MainWindow.UpdateWindowPos(Boolean updateEffectWindow) in D:\a\ClassIsland\ClassIsland\C ...
    at ClassIsland.MainWindow.UpdateTimerOnTick(Object sender. EventArgs e) in D:\a\ClassIsland\ClassIsland\ ...
    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback. Object args. Int32 num ...
    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source. Delegate callback. Object args. ...
```

### 应用版本

1.4.0.3-Firefly-10baa19(HEAD) (Core 1.4.0.0)

### 操作系统版本

Windows 11，在 22H2 和 23H2 上复现。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
已修复。
