### ISSUE TITLE
[功能请求]: 支持特定课程的隐藏选项

### ISSUE THREAD

**Issue by andycey** [ClassIsland/ClassIsland#179]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

晚自习时需要全屏显示作业内容，此时可以显示课表上的时间和倒计时，便于查看自习剩余时间。如果每次自习前单独调整上正课的时候容易忘记调回“全屏时隐藏窗口”，影响正常上课

### 想要实现或优化的功能

支持特定课程使用特定的窗口隐藏条件

**Comment by HelloWRC** [comment]
可能与 #96 重复？我打算在实现 #96 时也实现这个功能。

**Comment by DryIce-cc** [comment]
看起来已在 74f71803a2fdaf22494721641289687c0282f0bd 实现，支持特定课程使用特定的窗口隐藏条件。
目前还没有发布，您可以在 Actions 中下载体验。
