### ISSUE TITLE
[Bug]: 分割线会跳出来一个根本不存在的课程以及添加了一个会蹦出来好几个

### ISSUE THREAD

**Issue by ARanW97** [ClassIsland/ClassIsland#185]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

![捕获](https://github.com/ClassIsland/ClassIsland/assets/173707117/911f1e8d-1f7b-41e6-a90a-de1b7f89068f)
如图所示

### 期望的行为

更改掉这个分割线bug（跪求）

### 实际结果

在主界面和时间表中，仍位于原来位置，未按照所调整的时间进行调整，跳出一个时间很长的课程，但其实我并没有添加，且重启多次并无明显效果。
跪求作者修复 @He

### 应用版本

1.4.0.2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by wjj-8283** [comment]
有一个解决方法：将分割线种类转换为上课/课间，将开始时间和结束时间全部改成你想要改的时间，然后再转换为分割线

**Comment by wjj-8283** [comment]
分割线功能有一个bug：表面上分割线只有开始时间没有结束时间，实际上分割线有结束时间，只是被隐藏了，而且钉死在了初次创建的位置，当更改开始时间时，结束时间并没有跟着移动，引起这个bug
所以临时解决方案如上，希望作者尽快修复

**Comment by wjj-8283** [comment]
![捕获](https://github.com/ClassIsland/ClassIsland/assets/82750345/acc8ed0e-b8f4-4853-bd2c-0a89856c1502)

**Comment by wjj-8283** [comment]
解决方案截图：
![捕获](https://github.com/ClassIsland/ClassIsland/assets/82750345/12bc4320-2ac8-4ad1-9a5e-1c7918ac9bd4)
![捕获2](https://github.com/ClassIsland/ClassIsland/assets/82750345/8877fa37-743a-483c-93d2-755d5d561f2b)
![捕获3](https://github.com/ClassIsland/ClassIsland/assets/82750345/bcaffcf5-dbe3-4453-ad35-8a4a5568d0e7)
第一步：将分割线转换为上课/课间
第二步：改开始和结束时间
第三步：转换回分割线

**Comment by HelloWRC** [comment]
分割线目前是按照在时间表内的时间点顺序显示的，而非开始时间。目前计划在1.5改进调整分割线顺序的方式。

**Comment by YZX-Muggle** [comment]
(另外那个分割线所在区域如果没有在上课or课间休息时间段上，分割线会跑到整个课表最后面

**Comment by HelloWRC** [comment]
已修复。目前在查找当前时间点时会忽略分割线类型的时间点，将在后续改进分割线修改顺序的方式。（#153）

**Comment by DryIce-cc** [comment]
> 已修复。目前在查找当前时间点时会忽略分割线类型的时间点，将在后续改进分割线修改顺序的方式。（#153）

@HelloWRC 我正在写这方面的逻辑。分割线打算怎么改？
另外档案编辑代码真的好乱好乱好乱，有空可以拆分成像 SettingsWindowNew 那样的标签页抽屉吗（跪求
