### ISSUE TITLE
[功能请求]: 倒计时

### ISSUE THREAD

**Issue by lihans16** [ClassIsland/ClassIsland#186]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

想要个倒计时能显示在旁边的

### 想要实现或优化的功能

在课表右侧加个距离目标天数

**Comment by jiangyin14** [comment]
早已上线正式版
