### ISSUE TITLE
[Bug]: 如有损坏字体会导致点击“更改字体”下拉框后加载极度缓慢乃至死机

### ISSUE THREAD

**Issue by Qsgz2023ji5ban** [ClassIsland/ClassIsland#187]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

1. 无论选择哪一种取色方式
2. 系统存在一损坏字体
3. 点“更改字体”的列表
4. 等待

### 期望的行为

正常加载

### 实际结果

上方显示进度条（在移动）并一直不结束，点击窗体就会卡死

### 堆栈跟踪（可选）

```shell
崩溃后没有报告窗口弹出，所以无法填写日志
```

### 应用版本

1.4.1.2-Griseo-8b90b26(HEAD) (Core 1.4.0.0)

### 操作系统版本

Microsoft Windows 10.0.14393

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Qsgz2023ji5ban** [comment]
玄学哎，又好又不好的，估计字体渲染不出来有概率放弃？

感觉可以判断加载时长过长的话可以跳过，然后直接后面加上“已经损坏”？

**Comment by HelloWRC** [comment]
> 玄学哎，又好又不好的，估计字体渲染不出来有概率放弃？
> 
> 感觉可以判断加载时长过长的话可以跳过，然后直接后面加上“已经损坏”？

字体加载与渲染主要是由WPF负责的，我在字体选择界面中只告诉WPF要用哪些字体，没有很好的办法控制字体的加载和渲染过程，所以这个需求不太好实现。

**Comment by Qsgz2023ji5ban** [comment]
行，基本没法修我就关上了，反正一般人也没有如此离谱的字体。
