### ISSUE TITLE
[Bug]: 以兼容模式获取桌面壁纸失败

### ISSUE THREAD

**Issue by LiuYan-xwx** [ClassIsland/ClassIsland#188]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

目前表现为重启电脑后会获取失败，再次更换壁纸能正常获取

### 期望的行为

壁纸被正确获取

### 实际结果

壁纸获取失败
![屏幕截图 2024-06-28 102651](https://github.com/ClassIsland/ClassIsland/assets/66517348/8ee8c30f-e05f-4467-9422-cae00aaf6b8f)

### 堆栈跟踪（可选）

```shell
[2024/6/28 10:22:23] [Error] ClassIsland.Services.WallpaperPickingService:
以兼容模式获取壁纸失败。
System.IO.FileNotFoundException: D:\l\Part2\BB1oMrqx.j.jpg
   at System.Drawing.Image.FromFile(String filename, Boolean useEmbeddedColorManagement)
   at ClassIsland.Services.WallpaperPickingService.GetFallbackWallpaper() in D:\a\ClassIsland\ClassIsland\ClassIsland\Services\WallpaperPickingService.cs:line 181
```

### 应用版本

1.4.1.2

### 操作系统版本

Windows11 23H2 22631.3810

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
这个看起来是壁纸文件被删除了。兼容模式是按照壁纸文件获取的壁纸，文件没了当然是获取不了的。

**Comment by LiuYan-xwx** [comment]
> 这个看起来是壁纸文件被删除了。兼容模式是按照壁纸文件获取的壁纸，文件没了当然是获取不了的。

但是我记得文件一直是存在着的

**Comment by HelloWRC** [comment]
这个问题不属于ClassIsland本身的问题，我先关了。

**Comment by LiuYan-xwx** [comment]
> 这个问题不属于ClassIsland本身的问题，我先关了。

经检查确实是我自己的问题，感谢您的提醒，非常非常抱歉带来了麻烦。
