### ISSUE TITLE
[功能请求]: 显示多个快速信息

### ISSUE THREAD

**Issue by lihans16** [ClassIsland/ClassIsland#195]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

只能显示一个快速信息有点难受

### 想要实现或优化的功能

希望能加入多个快速信息，能排序最好

**Comment by DryIce-cc** [comment]
![image](https://github.com/ClassIsland/ClassIsland/assets/165131008/53e2ec84-8d69-4321-a2df-c51238a07514)
你说的「快速信息」是指这个？

**Comment by DryIce-cc** [comment]
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

请前往 应用设置—更新设置—更新通道，选择测试通道，然后进行更新。
然后回到此网页界面，点击 Close issue。

**Comment by jiangyin14** [comment]
警告⚠️
这已经不是您第一次提出重复的issue，下次提出功能请求前请先检查dev分支和master分支中是否已经实现，如再次提出已有功能的请求，可能面临被Blacklist的风险。
