### ISSUE TITLE
[Bug]: 在使用特定字体时，课程表会出现滚动条

### ISSUE THREAD

**Issue by LiuYan-xwx** [ClassIsland/ClassIsland#197]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

1. 更换字体

之前我使用的字体为**MiSans**
更换字体为这个[苹方字体](https://github.com/ZWolken/PingFang)后出现

### 期望的行为

应当正常显示，不会出现滚动条

### 实际结果

**异常情况:**
在课表右处会出现滚动条
![屏幕截图 2024-07-01 155836](https://github.com/ClassIsland/ClassIsland/assets/66517348/13047674-ea5c-4261-9860-5cda29d84ed8)
![屏幕截图 2024-07-01 155858](https://github.com/ClassIsland/ClassIsland/assets/66517348/899b2fac-0381-4848-86c2-ff6ed4d8cbd2)
**正常情况:**
![屏幕截图 2024-07-01 155919](https://github.com/ClassIsland/ClassIsland/assets/66517348/8c330d19-7dc8-4a6a-b6b6-0a56aa2d4fa0)
![屏幕截图 2024-07-01 155929](https://github.com/ClassIsland/ClassIsland/assets/66517348/55c8e1e7-2152-4678-a589-8b044da0f1ab)

### 应用版本

1.4.1.2

### 操作系统版本

Windows11 23H2 22631.3810

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by LiuYan-xwx** [comment]
噢不，dupe of #196 了()

**Comment by LiuYan-xwx** [comment]
我觉得是字体字形大小不同导致的文本超出窗口()
下方这一款字体虽然不会日常使用，但是可以看出问题，比正常字体小了一圈，课程的进度条与下方有明显距离。
![屏幕截图 2024-07-03 111623.png](https://github.com/ClassIsland/ClassIsland/assets/66517348/af447609-5dc6-4c2d-b007-42fe15111c96)

有没有更好的方法来显示主界面，避免这种问题呢？顺便完成一下 #80 ()

**Comment by HelloWRC** [comment]
已修复。
