### ISSUE TITLE
[Bug]: 在启用时间偏移后，课程表组件已过时间未应用偏移

### ISSUE THREAD

**Issue by LxHTT** [ClassIsland/ClassIsland#198]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

看了好几天都是这个样了  
课程表组件没有有应用时间偏移，但是时间组件有.  
课程表要切换到附加信息为已过时间/剩余时间.  

我设置的时间偏移是`-62`秒（

### 期望的行为

二者都应用偏移。

### 实际结果

只有时间组件生效，课程表组件的`时间点结束倒计时`功能正常，仅已过时间出现问题。

### 应用版本

1.4.1.2-Griseo-8b90b26

### 操作系统版本

Microsoft Windows 11 23H2 22631.3810

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by LxHTT** [comment]
版本号没写准（）  
就是现在Prerelease的那一个.

**Comment by DryIce-cc** [comment]
未能复现 @LxHTT 
附加信息只能精确到分钟，你的意思是二者相差一分钟？
附加信息为向上取整。

**Comment by LxHTT** [comment]
相差一分钟

**Comment by LxHTT** [comment]
![image](https://github.com/ClassIsland/ClassIsland/assets/98154001/7123daf0-c5e4-42ff-a812-ba6796ac022f)
如上，上课时间为8：52，实际时间与时钟组件偏移一分钟是正确的，但课程表组件参照的是实际系统时间。

**Comment by LxHTT** [comment]
但同时课程倒计时是正常的。

**Comment by Doctor-yoi** [comment]
已定位到问题点，位于ClassIsland/Services/LessonService.cs#L227 @HelloWRC

**Comment by DryIce-cc** [comment]
> ![image](https://private-user-images.githubusercontent.com/98154001/345244237-7123daf0-c5e4-42ff-a812-ba6796ac022f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5NzM1NDUsIm5iZiI6MTcxOTk3MzI0NSwicGF0aCI6Ii85ODE1NDAwMS8zNDUyNDQyMzctNzEyM2RhZjAtYzVlNC00MmZmLWE4MTItYmE2Nzk2YWMwMjJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAzVDAyMjA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdlODk1YjVmMWI3OGIzYzdlNGNlZWZkN2ZlYzlmZmNjZjU0MGJhNzhlMmEwNGNkN2RkNjZlOTc0Mzg4NzMzOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.z-QIkdi8_1Ed9ipWyh5bbLUFIM37w2s5TSM4fEko4Ms) 如上，上课时间为8：52，实际时间与时钟组件偏移一分钟是正确的，但课程表组件参照的是实际系统时间。

你是说附加信息应该显示 4/7min 吗？此处时间在源代码中的设计是向上取整的，与时间偏移无关。

你会注意到附加信息不会存在 0/7min，但存在长达一分钟的 7/7min。
你可以将时间偏移修改的大一点，可以更加直观地验证。

如果你觉得此处不应向上取整（巧了，我也这么认为），你可以将附加信息调至精确到秒的「倒计时」（等待合并pr）。

**Comment by HelloWRC** [comment]
未能复现这个问题，可能是由 https://github.com/ClassIsland/ClassIsland/issues/198#issuecomment-2205015056 所述的原因引发的。目前在 #191 中将【已过时间】的取整方式修改为向下取整，应该可以解决这个问题。

![image](https://github.com/ClassIsland/ClassIsland/assets/55006226/684493eb-4ead-4405-8b6e-569db389b070)
