### ISSUE TITLE
[Bug]: 点击托盘图标显示主菜单有延迟

### ISSUE THREAD

**Issue by DryIce-cc** [ClassIsland/ClassIsland#199]
![image](https://github.com/ClassIsland/ClassIsland/assets/165131008/0dd5cc73-f2cb-4833-9dbb-74a174afe1c8)
如上设置时，左键单击/触屏点击托盘图标，显示主菜单有延迟。
希望可以删除延迟，以便于操作。

**Comment by HelloWRC** [comment]
这个可能是我用的托盘菜单轮子的问题，我到时候调查一下

**Comment by DryIce-cc** [comment]
目前对照测试认为，可能是没有 禁用双击菜单 操作。

**Comment by HelloWRC** [comment]
已修复。
