### ISSUE TITLE
[Bug]: 在 编辑时间表并再次启用课表后，课后休息不会显示在课程表组件中

### ISSUE THREAD

**Issue by LxHTT** [ClassIsland/ClassIsland#201]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

1.停止启用课表  
2.编辑时间表  
3.启用课表

### 期望的行为

-

### 实际结果

-

### 应用版本

1.4.1.2-Griseo-8b90b26

### 操作系统版本

Microsoft Windows 11 23H2 22631.3810

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by DryIce-cc** [comment]
不只是课间休息，我上课呢它也不显示🤣
最近经常遇到，触发方式挺玄学的，不一定要编辑课表，有时多用用 ci 它就悄无声息地没了（

**Comment by HelloWRC** [comment]
已修复。
