### ISSUE TITLE
[Bug]: 小雨和中雨天气图标相同

### ISSUE THREAD

**Issue by andycey** [ClassIsland/ClassIsland#204]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

天气预报

### 期望的行为

小雨与中雨图标不同

### 实际结果

小雨与中雨图标相同，都为一个雨滴

### 应用版本

1.4.1.2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by LiuYan-xwx** [comment]
天气图标似乎是由小米天气api提供的

**Comment by HelloWRC** [comment]
> 天气图标似乎是由小米天气api提供的

天气图标我用的是 materialdesigninxaml 自带的，没有中雨和小雨单独的图标，只能用一个图标
