### ISSUE TITLE
[功能请求]: 主题色支持从屏幕上提取

### ISSUE THREAD

**Issue by DryIce-cc** [ClassIsland/ClassIsland#207]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

使主题色与ppt一致，可以更好地融入 ppt。
Office Powerpoint 全屏播放（“幻灯片放映”）和不全屏播放（“读取视图”）是两个不同窗口，导致目前无法将窗口设为 ppt。

### 想要实现或优化的功能

支持从整个屏幕上截图并提取主题色。

应用设置中的“主题色来源”添加“屏幕内容”，
提供和“系统壁纸”一样的亮度波峰选项、提取间隔选项、预览提取结果等。

**Comment by HelloWRC** [comment]
已实现。
