### ISSUE TITLE
[Bug]: 在经过 Pull#191 更改后，课程表组件`小时`时间部分向上取整导致显示错误

### ISSUE THREAD

**Issue by LxHTT** [ClassIsland/ClassIsland#209]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤
https://github.com/ClassIsland/ClassIsland/pull/191 的pr导致的。  
课间休息`11：50-14：30`应该是`2h40m`
![image](https://github.com/ClassIsland/ClassIsland/assets/98154001/594b79e3-524b-4244-83bf-1753cfc7796d)

### 期望的行为

-

### 实际结果

-

### 应用版本

1.4.1.2-Griseo-bd7035b

### 操作系统版本

Microsoft Windows 11 23H2 22631.3810

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by DryIce-cc** [comment]
非常抱歉，我们修改后没有进行过严格测试。您可以将
ClassIsland.Core/Converters/SecondsLongToFormatStringConverters.cs
的第十四行改为
            >= 3600 => $@"{v.Hours}h{Round(v.TotalMinutes % 60.0)}m",

**Comment by LiuYan-xwx** [comment]
遇到了

**Comment by LiuYan-xwx** [comment]
还有时间点附加信息无法切换和关闭的问题

**Comment by DryIce-cc** [comment]
> 还有时间点附加信息无法切换和关闭的问题

没遇见过此问题，您可能要检查一下档案编辑里有没有调整过时间点附加信息的特定显示设置。

**Comment by LxHTT** [comment]
> 还有时间点附加信息无法切换和关闭的问题

无法复现。

**Comment by LiuYan-xwx** [comment]
🤔🤔我回去再检查一下吧

**Comment by HelloWRC** [comment]
已修复。
