### ISSUE TITLE
[Bug]: 应用设置 > 隐私 > 此处 超链接跳转时报错

### ISSUE THREAD

**Issue by KaguReion** [ClassIsland/ClassIsland#216]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

启动 ClassIsland 并打开应用设置 > 隐私，点击右侧「匿名使用情况分析」下面的「此处」超链接，ClassIsland 唤起浏览器到对应页面，但同时报错「无法导航到 ：Invalid URI: The URI is empty.」

![报错页面](https://github.com/user-attachments/assets/2fcb29fe-c691-42a5-8735-9e05df188f16)

### 期望的行为

唤起页面时不应报错。

### 实际结果

唤起页面时报错。

### 应用版本

1.4.2.2-Griseo-9337800(HEAD) (Core 1.4.0.0)

### 操作系统版本

22631.3880

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
已修复。
