### ISSUE TITLE
[Bug]: 更新到最新的开发版1.4.2.2后无法正常进行放学提醒

### ISSUE THREAD

**Issue by wjj-8283** [ClassIsland/ClassIsland#218]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

制作时间表，等待放学

### 期望的行为

放学时发出放学提醒

### 实际结果

放学的时候没有任何提醒，重新开启放学提醒、重启应用、重装（强制更新）均无效
临时解决方案：在后面加一段课间休息，把它处理成下课提醒，但是看着很难受

### 堆栈跟踪（可选）

```shell
无
```

### 应用版本

1.4.2.2-Griseo-9337800

### 操作系统版本

10.0.26100.1150，Windows 11 企业版LTSC

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by wjj-8283** [comment]
我启用过最新的实验性功能，不知道是不是这个问题

**Comment by HelloWRC** [comment]
此问题已经在 https://github.com/ClassIsland/ClassIsland/commit/45855f6d7abc17549f4ab4a473ff9d8322227324 修复，请等待下一次更新。目前临时的解决方案是暂时不使用实验课表组件。
