### ISSUE TITLE
[功能请求]: 在帮助文档中添加classisland://的所有URL及其对应的操作一览表

### ISSUE THREAD

**Issue by wjj-8283** [ClassIsland/ClassIsland#219]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

我想要将几个常用功能添加桌面快捷方式，方便快捷访问，但是我对classisland://的相关语法丝毫不知道……

### 想要实现或优化的功能

希望开发者能够公开所有的classisland://的URL及其对应的操作，并以表格的形式写入帮助文档中

**Comment by HelloWRC** [comment]
已完成：https://docs.classisland.tech/zh-cn/latest/app/uri-navigation/
