### ISSUE TITLE
[Bug]: [随机触发]课程表（实验）组件会将所有课程全部展示（忽略是否隐藏）

### ISSUE THREAD

**Issue by wjj-8283** [ClassIsland/ClassIsland#220]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

在时间表中将部分课程设置为隐藏，然后添加课程表（实验）组件到主界面，并启用实验性功能

### 期望的行为

按照常规，设置为隐藏的课程只会在到达时间点后才出现
![image](https://github.com/user-attachments/assets/f0afe24b-25b0-4c9f-b663-42f6e7eabc58)

### 实际结果

课程表展示了所有课程，不管是否隐藏
![image](https://github.com/user-attachments/assets/7df7f86b-e600-4401-8fd1-9594125764f0)
此bug随机触发，有的时候显示又是正常的

### 堆栈跟踪（可选）

```shell
无
```

### 应用版本

1.4.2.2-Griseo-9337800

### 操作系统版本

10.0.26100.1150，Windows 11 企业版LTSC

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
这个问题我尝试修复了以下，理论上应该没问题了。如果还能复现的话请重新开启这个议题。
