### ISSUE TITLE
[功能请求]: 增加竖直版本island的支持

### ISSUE THREAD

**Issue by wjj-8283** [ClassIsland/ClassIsland#223]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

有的老师制作ppt时一部分内容会被位于顶部的主界面遮挡，且有的老师个子偏矮，够不到顶部，放在下面又看着很奇怪

### 想要实现或优化的功能

添加竖版island的支持，以允许用户将主界面贴靠在左侧/右侧

**Comment by HelloWRC** [comment]
要做竖版的话需要重新适配所有组件，实现起来不太现实，故暂不考虑实现此功能。

**Comment by wjj-8283** [comment]
好吧……只能期待未来有大佬通过插件实现了……

**Comment by DryIce-cc** [comment]
可以使用 [zongzitek](https://github.com/STBBRD/ZongziTEK-Blackboard-Sticker) 实现。
![Image_1721968482094](https://github.com/user-attachments/assets/e792ef61-608b-440b-86eb-f179329320b9)
