### ISSUE TITLE
可以调整课表的上下宽度

### ISSUE THREAD

**Issue by jerjjj** [ClassIsland/ClassIsland#225]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

当课程较多时，为了使课程表在第1行，显示完全会将缩放调小,但此时字过小，导致后面的同学看不清,增加剩下的宽度就有助于减轻这个麻烦

### 想要实现或优化的功能

增加调节上下宽度的选项

**Comment by DryIce-cc** [comment]
@jerjjj 没看懂您的需求。“上下宽度”是指允许多行显示吗？
另外，请勿删除“[功能请求]”前缀。

**Comment by jerjjj** [comment]
> Quote reply

允许多行显示会更好

**Comment by DryIce-cc** [comment]
> 允许多行显示会更好

与 #181 重复，如果阁下的 issue 仅有此请求，可以自行以 not planned 关闭。
