### ISSUE TITLE
[Bug]: 启用“课程表（实验）”后失去放学提醒

### ISSUE THREAD

**Issue by Qsgz2023ji5ban** [ClassIsland/ClassIsland#229]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

非常正常的在使用课表直到放学
课程表启用了放学提醒
没有使用“实验性功能”，只启用了“课程表（实验）”

### 期望的行为

弹出放学提醒

### 实际结果

啥事没有，下课都没报

### 堆栈跟踪（可选）

```shell
啥也没有
```

### 应用版本

1.4.2.2-Griseo-9337800(HEAD) (Core 1.4.0.0)

### 操作系统版本

Windows 10 企业版 LTSC 19044.4651

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
与 #218 重复
