### ISSUE TITLE
[Bug]: 程序窗体神秘“蒸发”，但是仍能找到进程

### ISSUE THREAD

**Issue by Qsgz2023ji5ban** [ClassIsland/ClassIsland#230]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

环境和 #229 一致
正常的上着课（管理员身份运行）

### 期望的行为

正常工作

### 实际结果

过了一会之后神奇“蒸发”，即使打开**设置或其他窗体界面挂在后台不关上也会引发BUG**。
但是，从任务管理器里仍能看见`ClassIsland.exe`**正在运行且并没有未响应**
点主程序运行也会报告“已存在一个实例”
![image](https://github.com/user-attachments/assets/69f0e47b-98ef-41c2-9693-8b90ae8c9c06)
*任务栏不存在和任务管理器里仍能看见的截图*

### 堆栈跟踪（可选）

```shell
啥也没有
```

### 应用版本

1.4.2.2-Griseo-9337800(HEAD) (Core 1.4.0.0)

### 操作系统版本

Windows 10 企业版 LTSC 10.0.19044.4651

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Qsgz2023ji5ban** [comment]
![image](https://github.com/user-attachments/assets/d26e5991-aec2-48b6-baf1-ce84b74c5de3)
*主界面和任务栏截图 *

**Comment by Qsgz2023ji5ban** [comment]
这台电脑还在`LTSC 2019`上遇见过相同问题，同时伴有所有应用频闪，不稳定。怀疑是其他应用的锅，于是就“干净”安装了`LTSC 2021`，其他应用不闪了，但`ClassIsland`仍无法正常工作。

**Comment by DryIce-cc** [comment]
主界面、托盘图标、后台挂着的应用设置窗口都没了是吧？

**Comment by DryIce-cc** [comment]
启动时任务栏卡了的话，托盘图标会创建失败；
主菜单即使设为置顶，有的窗口（比如希沃授课助手投屏 / uwp 全屏）也会比它高；
另外检查下隐藏窗口的设置；
别的没啥能说的了，这真是玄学问题。基本无解。

**Comment by Qsgz2023ji5ban** [comment]
任务栏正常，没有置顶和置底窗口（ci置底），没隐藏窗口，用的鼠标没放上去隐藏

**Comment by Qsgz2023ji5ban** [comment]
> 启动时任务栏卡了的话，托盘图标会创建失败； 主菜单即使设为置顶，有的窗口（比如希沃授课助手投屏 / uwp 全屏）也会比它高； 另外检查下隐藏窗口的设置，以及仔细检查一下手指有没有碰到主界面导致其隐藏； 别的没啥能说的了，这真是玄学问题。基本无解。

那可有意思了，真就闹鬼呗🤣

**Comment by Qsgz2023ji5ban** [comment]
这个还挺玄学
另外一个测试ecs的同机同软件同系统版本的系统
竟然能在开着ecs的同时正常使用ci（开了ecs的置顶后玄学的原地复活，所有一下子弹出来了，魔法🔮）
另外一台AMD的古董，同软件同系统版本运行啥事没有

**Comment by Qsgz2023ji5ban** [comment]
![魔法展示](https://github.com/user-attachments/assets/bb49f40e-f6d6-4bb6-a483-7c69b12a8fc6)

**Comment by Qsgz2023ji5ban** [comment]
这回更神奇，前台好端端的设置窗口原地“蒸发”
没错，前台窗口

**Comment by Qsgz2023ji5ban** [comment]
稍等，貌似只要放到`Program Files`等带空格的文件夹都会这样

**Comment by Qsgz2023ji5ban** [comment]
好像没事了（

貌似只要内存满了就这样，这是个老BUG

**Comment by HelloWRC** [comment]
已修复。
