### ISSUE TITLE
[Bug]: 新课程表组件不会提示`今天没有课程。`

### ISSUE THREAD

**Issue by LiuYan-xwx** [ClassIsland/ClassIsland#233]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

1. 在组件库使用新的课程表组件
2. 确保今日无课程

### 期望的行为

应该与旧课程表组件保持一致，当今日无课程时显示`今天没有课程`

### 实际结果

不会提示，以下为截图
新的：
![Snipaste_2024-07-31_15-17-14](https://github.com/user-attachments/assets/077b8ce8-743c-423d-8046-dbe3c0acbca6)
旧的：
![Snipaste_2024-07-31_15-17-39](https://github.com/user-attachments/assets/fad280c3-f6a2-418c-9791-11456c77f65e)

### 应用版本

1.4.2.2-462c97c(dev)

### 操作系统版本

Windows10 22H2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by DryIce-cc** [comment]
我觉得删了没毛病啊…

**Comment by LiuYan-xwx** [comment]
> 我觉得删了没毛病啊…

我怎么觉得挺好的（（
毕竟如果没课那里会空一截（（

**Comment by DryIce-cc** [comment]
> > 我觉得删了没毛病啊…
> 
> 我怎么觉得挺好的（（ 毕竟如果没课那里会空一截（（

））也许可以让没有显示内容的组件隐藏得更彻底一些

**Comment by LyCecilion** [comment]
我以为这是 feature 呢（逃

**Comment by HelloWRC** [comment]
已实现显示占位符。
