### ISSUE TITLE
[功能请求]: 建议加入常驻课表功能

### ISSUE THREAD

**Issue by RANRANlovely** [ClassIsland/ClassIsland#242]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

学校补课的课表一直用的是同一个，设置起来非常麻烦

### 想要实现或优化的功能

加入一个常驻课表，使得用户可以让软件一直执行该课表

**Comment by DryIce-cc** [comment]
此功能是否可以通过 #243 设置一周七天、不分单双周实现？
#243 更为普适一些，这个先关了哈。
