### ISSUE TITLE
[功能请求]: 希望能有一个待办提醒的版本

### ISSUE THREAD

**Issue by Helium-327** [ClassIsland/ClassIsland#246]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

希望能有一个待办提醒的版本，当前桌面端没有一个很好用的任务待办提醒的软件，感觉这个项目可以修改成该类软件。以便于提高工作效率

### 想要实现或优化的功能

- 添加待办
- 更改待办
- 语音提醒待办任务开始

**Comment by Qsgz2023ji5ban** [comment]
但是这个项目终究是`classisland`哎😅目标是电子课表（）
你到时候可以看看未来有没有人给您这个想法写个插件？

**Comment by DryIce-cc** [comment]
> 当前桌面端没有一个很好用的任务待办提醒的软件

ms Todo 之类的软件有很多吧…

**Comment by Helium-327** [comment]
感觉这个软件固定在桌面，挺适合做todo类功能的，课表其实也可以有todo

**Comment by DryIce-cc** [comment]
> 感觉这个软件固定在桌面，挺适合做todo类功能的，课表其实也可以有todo

这个软件的主要开发目标是在校使用的。
在校使用不是很需要有待办事项功能，亦不方便有过多的交互。
我们欢迎[编写插件](https://docs.classisland.tech/zh-cn/latest/dev/plugins/create-project/)实现任何功能，但主程序不会考虑实现。

> 希望能有一个待办提醒的版本

听描述，你应该是希望能使本软件的外观，搭配一套待办事项的功能内核。
这个点子与软件的自身功能没有关联，不适合放在 issue 里。
如有需要，你可以通过 Convert to discussion 到讨论区进行分享。
