### ISSUE TITLE
[Bug]: “准备上课”和“上课”提醒紊乱

### ISSUE THREAD

**Issue by Qsgz2023ji5ban** [ClassIsland/ClassIsland#250]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

1. 我的时间表第一节是课间
2. 在两分钟准备上课提示的时间内退出ClassIsland
3. 重新打开ci

### 期望的行为

先显示“课间休息”再“准备上课”。

### 实际结果

先显示“课间休息”然后突然“上课”再“准备上课”。

### 应用版本

1.4.3.1-Griseo-5eb7dc7(HEAD) (Core 1.4.0.0)

### 操作系统版本

Microsoft Windows 10.0.22623

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by HelloWRC** [comment]
已修复。
