### ISSUE TITLE
[Bug]: 更新 会导致 课表 时间表 科目 被清空

### ISSUE THREAD

**Issue by UGYnpU2nuB8QCFqDrsWZgmxMBp43WQ** [ClassIsland/ClassIsland#251]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

安装1.4.0.4版，更新到1.4.3.1

### 期望的行为

增加警告，尤其是在发版的文件名和描述中，并主动备份档案

### 实际结果

课表 时间表 科目被清空
![图片](https://github.com/user-attachments/assets/3743d82b-b5a0-441e-9b2f-239c2f0b0d38)
![图片](https://github.com/user-attachments/assets/9214581e-30f5-4045-9474-f1e60cc5f652)
![图片](https://github.com/user-attachments/assets/e16040ce-a701-4c6e-a75c-0c00f9adb92d)

### 应用版本

1.4.3.1

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by Qsgz2023ji5ban** [comment]
@UGYnpU2nuB8QCFqDrsWZgmxMBp43WQ 是否原来的配置文件选择了非`Default.json`？有的话再切换回去，没有的话，请把profile文件夹下的`Default.json.bak`重命名为`Default.json`并覆盖试试。

> 更新丢档很常见了……我都不知道丢几回了

**Comment by UGYnpU2nuB8QCFqDrsWZgmxMBp43WQ** [comment]
> @UGYnpU2nuB8QCFqDrsWZgmxMBp43WQ 是否原来的配置文件选择了非`Default.json`？有的话再切换回去，没有的话，请把profile文件夹下的`Default.json.bak`重命名为`Default.json`并覆盖试试。
> 
> > 更新丢档很常见了……我都不知道丢几回了

我的配置文件是"Default.json"，而且我发现1.4.3.1版会自动覆盖里面的"Default.json"和"Default.json.bak"

**Comment by HelloWRC** [comment]
貌似这个问题只在默认档案`Default.json`上发生？在修复之前可以另外新建一个档案来缓解这个问题。

**Comment by Qsgz2023ji5ban** [comment]
> 貌似这个问题只在默认档案`Default.json`上发生？在修复之前可以另外新建一个档案来缓解这个问题。

但是更新的时候会有概率自己回到`Default.json`……又是另外一种BUG了

**Comment by Qsgz2023ji5ban** [comment]
有些时候重启都会丢档……
这边推荐临时解决方案：任务计划+批处理备份
一丢档就恢复
> 其实ClassIsland在开始更新**前**备份一次到`UpdateTemp`下`backups`文件夹，这样丢档就好办了

**Comment by HelloWRC** [comment]
已修复。

**Comment by onear233** [comment]
实测并未修复，1.4.2.2->1.4.3.1更新之后仍然会导致所有数据被清空，并且备份了原来的Default.json之后，覆盖default.json，重启无效，重命名default.json，在档案管理里无法选择此json

**Comment by DryIce-cc** [comment]
> 实测并未修复，1.4.2.2->1.4.3.1更新之后仍然会导致所有数据被清空，并且备份了原来的Default.json之后，覆盖default.json，重启无效，重命名default.json，在档案管理里无法选择此json

@onear233 修复暂时还没有发布到任何通道，用[这个版本](https://github.com/ClassIsland/ClassIsland/actions/runs/10437584120)试一下
