### ISSUE TITLE
大号字体模式

### ISSUE THREAD

**Issue by HelloWRC** [ClassIsland/ClassIsland#26]
在主界面使用更大的字体，缩小元素间距

**Comment by Qsgz2023ji5ban** [comment]
貌似与 #80 重复，建议关闭

**Comment by DryIce-cc** [comment]
![image](https://github.com/user-attachments/assets/2ffcdb00-4bee-4e63-85f1-a607b17974e7)

试了一下，整不来整不来，主要是放大字体大小同时缩小边距的分量不太好把握，不知道有没有什么解决方案。

> @Qsgz2023ji5ban 貌似与 #80 重复，建议关闭

还真是，#80 的字体大小就是这个 issue 的无极调节版。

**Comment by HelloWRC** [comment]
这个feature 我本来是想和主题一起做的（），因为调整字体大小之后还得对边距做一定的调整，用主题的话可以更灵活地实现
。但1.5东西太多，显然主题功能不可避免地要跳票了……只能等后续版本实现了。

**Comment by HelloWRC** [comment]
> 试了一下，整不来整不来，主要是放大字体大小同时缩小边距的分量不太好把握，不知道有没有什么解决方案。

或许可以考虑在布局时减少边距的使用，更多地采用对齐之类的布局方式？

**Comment by DryIce-cc** [comment]
> 或许可以考虑在布局时减少边距的使用，更多地采用对齐之类的布局方式？

让我再努力一下 🤕 再整不出来大不了换回 ecs…

**Comment by HelloWRC** [comment]
已实现。
