### ISSUE TITLE
无论进行何种课程修改，都没能即时刷新课表

### ISSUE THREAD

**Issue by Qsgz2023ji5ban** [ClassIsland/ClassIsland#265]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

应该是改了就能同步在主界面课表显示的
但是永久换课相较于临时换课，后者约等于新建了个课表，所以就是重载了。
（所以我推测， **档案编辑里也会有相同问题** ）

### 实际结果

但是并没有像不勾选”永久换课“那样直接同步更改到显示的课表，需要重启ci才行

### 重现步骤

进行换课，同时勾选”永久换课“

### 应用版本

1.4.4.0-Griseo-c98d7d8(HEAD) (Core 1.4.0.0)

### 操作系统版本

Microsoft Windows 10.0.22623

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by Qsgz2023ji5ban** [comment]
实测，档案编辑也有此`bug`。

**Comment by Qsgz2023ji5ban** [comment]
https://github.com/user-attachments/assets/5f4048fc-7f61-4aef-acc8-99a229ff2c81

**Comment by HelloWRC** [comment]
已修复。
