### ISSUE TITLE
正确更新完成之后请求是否删除下载的新版本压缩包

### ISSUE THREAD

**Issue by Qsgz2023ji5ban** [ClassIsland/ClassIsland#269]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/zh-cn/latest/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/zh-cn/latest/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

教室电脑为了C盘的祥和，D盘现在只剩500MB了……
（主要是塞了个VS2022，以及作为我校私立ftp服务器。别问为什么）剩下的文件老师全不让删，放网盘里`WPS`打开时会爆炸（报错+文件丢失）
今天提交作业时查看了一下，突然发现虽然更新压缩包解压的目录下已经删除了文件了，但是压缩包还在
（可能有人觉得很小……但是这个压缩包大小是3个英语课件那么大啊）

### 想要实现或优化的功能

更新完成后弹出提示，让用户确认是否删除
（其实能看见更新完成通知就可以删了……但是以防万一？）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by Qsgz2023ji5ban** [comment]
![image](https://github.com/user-attachments/assets/9f542a1a-2ca4-4acb-bf07-34aea9b1aa0e)
上面的文件夹是空的，但是还有下面的压缩包……

**Comment by HelloWRC** [comment]
已修复。
