### ISSUE TITLE
ProfileAnalyzeService 中存在几处 NullReferenceException 问题

### ISSUE THREAD

**Issue by DryIce-cc** [ClassIsland/ClassIsland#282]
`ProfileAnalyzeService.cs` 有几处逻辑可能触发 `NullReferenceException`，暂时打了临时补丁，可能需要进一步修复。

- 169 行：`node.Target`未初始化？
复现过程：新建档案，查看任意科目的继承情况。

- 191 和 208 行：`x.Object`为 null
复现过程：新建课表，不选择时间表，查看继承情况。

**Comment by Qsgz2023ji5ban** [comment]
挖的坑迟早要自己填（雾

**Comment by Qsgz2023ji5ban** [comment]
建议直接告知，要求选择时间表？

**Comment by HelloWRC** [comment]
已修复。
