### ISSUE TITLE
设置窗口`基本-行为-显示启动加载界面`下面的两个文本框不同宽

### ISSUE THREAD

**Issue by Qsgz2023ji5ban** [ClassIsland/ClassIsland#283]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

左对齐或者同宽

### 实际结果

![image](https://github.com/user-attachments/assets/a32b4661-c691-45f5-aa4b-8b45612070a8)

### 重现步骤

点击展开再填上上面的输入框（较长文本）

### 堆栈跟踪（可选）

```shell
那必然是没有的。
```

### 应用版本

1.4.4.0-Griseo-c98d7d8(HEAD) (Core 1.4.0.0)

### 操作系统版本

Microsoft Windows 10.0.22623

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by Qsgz2023ji5ban** [comment]
随手画了两条线，甚至不画也很清楚

**Comment by LiuYan-xwx** [comment]
改为左对齐(?

**Comment by DryIce-cc** [comment]
默认是对齐的，如果文字过长会延伸。
![image](https://github.com/user-attachments/assets/bc1db8f5-ae4b-4cae-a32e-1730fc8aa5f5)

**Comment by Qsgz2023ji5ban** [comment]
好的，迁移到discussion
