### ISSUE TITLE
添加一个可以显示次日课程表的组件

### ISSUE THREAD

**Issue by ltdq** [ClassIsland/ClassIsland#290]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/zh-cn/latest/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/zh-cn/latest/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

在晚自习期间需要查看**次日**课表

现在方案是每天晚上**手动**切换到第二天的课表

新版本 Classisland 推出了**按规则隐藏组件**功能

感觉可以通过新的显示次日课表组件配合这个功能实现特定时间段**同时**显示**次日**课表和**本日**课表。

### 想要实现或优化的功能

需要一个在特定时间段显示**次日**课程表的课程表，等同于非动态的当前模式课表（不显示课程进度等附加信息）， 需要一个标题**《明日课程》**，还需要考虑**轮换**问题

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by Qsgz2023ji5ban** [comment]
与 #288 貌似相同？看起来 #288 +显示条件就是这个

**Comment by liuziheng20091106** [comment]
我觉得可以这么弄:
课程表组件中可以选择显示昨日或当日或次日或+2日课程表。
这样添加两个课程表，第二个选择次日并且设置晚自习时间显示，第一个在晚自习事选择仅显示当前课程。

**Comment by HelloWRC** [comment]
已实现。
