### ISSUE TITLE
1.4.5.1版本在Win11环境下闪退

### ISSUE THREAD

**Issue by undefftr** [ClassIsland/ClassIsland#305]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

现在是8:00，距离开学还有1/24天。 我在我的Win11工作站上打开了ClassIsland，并且准备写时间表。

### 实际结果

噔噔咚

闪退且没有报错弹窗

### 重现步骤

1. 打开一个无任何配置的ClassIsland实例
2. 走完欢迎流程
3. 闪退

### 应用版本

1.4.5.1-Griseo-后面我也不知道因为已经闪退了

### 操作系统版本

10.0.22630.4037

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
抓取错误日志试试看 https://docs.classisland.tech/zh-cn/latest/app/reporting-issue/#%E6%94%B6%E9%9B%86%E6%97%A5%E5%BF%97

**Comment by DryIce-cc** [comment]
额，原来 win11 的版本号开头是 10 吗

**Comment by undefftr** [comment]
```
Application: ClassIsland.exe
CoreCLR Version: 8.0.724.31311
.NET Version: 8.0.7
Description: The process was terminated due to an internal error in the .NET Runtime at IP 0x00007FFC3F0A87A0 (0x00007FFC3F050000) with exit code 0x80131506.
```

**Comment by DryIce-cc** [comment]
@undefftr 重新安装运行时试试
https://dotnet.microsoft.com/zh-cn/download/dotnet/thank-you/runtime-desktop-8.0.8-windows-x64-installer

**Comment by HelloWRC** [comment]
这个问题应该可以通过更新 .NET 运行时解决。如果问题已经解决了，那我就先把这个 issue 关了。

**Comment by undefftr** [comment]
closed，因为昨天它莫名其妙好了，甚至自动添加了开机自启（
