### ISSUE TITLE
最新测试版在各种设置界面中无法使用触屏滚动

### ISSUE THREAD

**Issue by wwweeer** [ClassIsland/ClassIsland#306]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

正常使用触摸屏滑动

### 实际结果

普通界面和时间表均无法使用触屏滚动，手指移动效果同左键按下移动。

### 重现步骤

正常使用触摸屏滑动时

### 应用版本

1.4.5.1

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by wwweeer** [comment]
补充：仅能够使用窗口右侧的滑动条滚动内容

**Comment by MKStoler4096** [comment]
~~欸原来不止我这个样吗~~
我们这里也一样，系统版本1607

**Comment by HelloWRC** [comment]
已修复。

**Comment by DryIce-cc** [comment]
此问题在周二可以稳定复现（包括重启设备），到今天已无法复现。期间应该没有任何设置改动。🤔
