### ISSUE TITLE
提醒弹出不正常

### ISSUE THREAD

**Issue by HUSX100** [ClassIsland/ClassIsland#307]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

我平时设置将 classisland 置底，但是打开了提示的置顶功能，所以弹出的提示应当显示在老师的 ppt 上方

### 实际结果

在应当提示的时候，提醒依旧显示在其他窗口下方

### 重现步骤

1.将软件默认位置设置为置底
2.在“提醒”选项卡中打开提醒置顶以及自动启用
3.在提醒时，弹出的提醒并未置顶

### 应用版本

最新 dev 版

### 操作系统版本

22621

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
~~用管理员模式运行了吗？~~

老Bug，从1.4.0.4开始就有了……

**Comment by ZhiZaiDuoFang** [comment]
确实，我还在想是哪个设置出问题了……

**Comment by HelloWRC** [comment]
已修复。
