### ISSUE TITLE
windows7设置环境变量导致希沃白板不能正常使用

### ISSUE THREAD

**Issue by guoruiqi123456** [ClassIsland/ClassIsland#309]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

windows7设置环境变量
setx DOTNET_GCName clrgc.dll
setx DOTNET_EnableWriteXorExecute 0
希望在使用classisland的同时使用写哦白班

### 实际结果

windows7设置环境变量
setx DOTNET_GCName clrgc.dll
setx DOTNET_EnableWriteXorExecute 0
希沃白板不能正常使用，希沃白板打开没有任何反应，任务管理器也没有相应的进程

### 重现步骤

1.首先，打开cmd；
2.其次，相应输入
setx DOTNET_GCName clrgc.dll
setx DOTNET_EnableWriteXorExecute 0
3.然后打开希沃白板

### 应用版本

1.4.0.4

### 操作系统版本

windows7旗舰版，版本6.1（内部版本7601：service park 1）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by Doctor-yoi** [comment]
classisland正在针对.net6进行适配，目前已创建仓库并发布第一个开发者测试版，近期会发布第一个针对主仓库master分支的.net6适配版release
详细进度详见[ClassIsland/ClassIsland-net6](https://github.com/ClassIsland/ClassIsland-net6)

**Comment by HelloWRC** [comment]
很抱歉我没有仔细测试此修复方法的兼容性，目前正在进行可以直接正常在 windowd 7 上运行的 .net 6 版本适配。可以先删除此环境变量，然后通过 powershell 或 cmd 脚本在启动时手动设置局部的环境变量暂时解决这个问题。
