### ISSUE TITLE
小组件堆叠＆自动轮播

### ISSUE THREAD

**Issue by jing-gou** [ClassIsland/ClassIsland#310]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/zh-cn/latest/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/zh-cn/latest/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

屏幕大小有限，放置超过两个组件就会显得较为拥挤，是否可以实现像小组件堆叠，自动轮播小组件

### 想要实现或优化的功能

小组件堆叠，自动轮播小组件

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
Zongzitek 已有此功能，您可以尝试一下用用。

iOS 的小组件堆叠，建立在「智能叠放」和「可手动切换」的基础上，而 ClassIsland 不具备这两个条件。
因而我感觉实际在学校中，组件轮播并不实用。
用户只会在「需要快速信息」时，比如查看日期：扫一眼 ClassIsland 便可获取
如果抬头还要等好几秒才能得到想要的信息，未免有失「快速信息」的初衷。
过于频繁的切换，也可能造成老师反感。

**Comment by Jursin** [comment]
我也有这样的需求，组件放多后超出屏幕边缘，而暂时无法调整文字间距，只能通过组件轮播以显示更多信息，虽然可能失去快速信息初衷，但可以作为可选功能

**Comment by HelloWRC** [comment]
已实现。
