### ISSUE TITLE
（在这里输入你的标题）时间显示不正常

### ISSUE THREAD

**Issue by kiyana0** [ClassIsland/ClassIsland#315]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

时间显示出现问题，如图
![微信截图_20240907133203](https://github.com/user-attachments/assets/61602c2e-ac8d-461b-91d9-8b7d81039535)

### 实际结果

本应出现在科目下的时间出现在了正中间，且只有时间无科目名称，上课和下课提示不正常

### 重现步骤

时间处于周六下午（上午未出现问题），在设定的13：30结束的课间休息结束后，课前提示未显示，时间变为图片所示

### 应用版本

1.4.0.4

### 操作系统版本

Windows10希沃定制版

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
此问题早已在 1.4.5 修复。

**Comment by kiyana0** [comment]
抄收了，感谢您的回复，现已使用1.5.0版本，暂未发生问题，如出现问题我将及时向您反馈，感谢您的答复。
73
________________________________
发件人: HelloWRC ***@***.***>
发送时间: 2024年9月8日 0:00
收件人: ClassIsland/ClassIsland ***@***.***>
抄送: kiyana0 ***@***.***>; Author ***@***.***>
主题: Re: [ClassIsland/ClassIsland] （在这里输入你的标题）时间显示不正常 (Issue #315)


Closed #315<https://github.com/ClassIsland/ClassIsland/issues/315> as not planned.

―
