### ISSUE TITLE
睡眠后重新登录无法打开设置中的外观页面

### ISSUE THREAD

**Issue by zhoucAndrew** [ClassIsland/ClassIsland#318]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

睡眠后重新登录仍可正常打开设置中的外观页面

### 实际结果

没有正常打开（卡死），新版本中卡死后再重新打开设置白屏

### 重现步骤

1. 首先打开一遍外观页面
2. 关闭设置
3. 睡眠
4. 重新打开设置页面
5. 打开外观（此时已卡，其他标签页仍能正常打开）
6. 关闭设置页面，并重新打开（白屏，重启ClassIsLand后恢复）

### 应用版本

1.5.0.0

### 操作系统版本

10.0.22631.4112

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
与 #92 重复，无法修复
