### ISSUE TITLE
下课时的“课间提醒”在“课间后无课程”时错误显示

### ISSUE THREAD

**Issue by meowluna** [ClassIsland/ClassIsland#322]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

在最后一节课下课时，只显示课间时长/不显示课间提醒

### 实际结果

在最后一个课间且后面无课程时，前一节课下课时的”课间提醒“显示”下节课程“仍为前节课程
如图所示，当前课程为15:10-15:50，当前时间为15:50+，当前课程已下课，课间提醒显示下节课程仍为当前课程
![aa10f860544af60692f6a69b9d9794f0](https://github.com/user-attachments/assets/08cfbe9a-f2e3-4927-8686-fd41e339d09c)
最后一节课程后存在课间在某些情况下可能存在需求，但无论最后一节课程后是否可以添加课间，课间提醒的”下节课程“都不应该错误显示为上节课程，如在最后一节课程后添加课间为不被允许的行为，则应当在保存时间表时指出/报错，或在任何适当的位置进行提示/限制，而不是自由编辑导致显示错误。

### 重现步骤

在最后一节课程后存在课间

### 应用版本

1.5.0.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
已修复！现在放学前的课间提醒只显示标题，不会显示提醒内容。
