### ISSUE TITLE
在Windows11 23H2中，应用设置-组件 触摸拖动组件库及组件会出现长时间加载，类似卡死

### ISSUE THREAD

**Issue by qiyao11** [ClassIsland/ClassIsland#326]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

触摸拖动组件应正常调整组件顺序或添加组件

### 实际结果

窗口卡在加载，不可点击或关闭，一段时间后或接入外接鼠标或使用虚拟触摸板恢复

### 重现步骤

重现：在Windows11，未外接鼠标的情况下，打开应用设置-组件，触摸拖动任意组件或组件库的组件会导致长时间加载，类似卡死

### 应用版本

1.5.0.0

### 操作系统版本

22631.3527

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by Jursin** [comment]
貌似不止Win 11,Win 10也存在，而且好像就正式版1.5.0.0有，之前测试版没有这个问题

**Comment by HelloWRC** [comment]
这个问题很可能是由 https://github.com/ClassIsland/ClassIsland/commit/107a32597a2576b9c8be9dee9442092d692ef5d4 引起的，我到时候回滚一下

**Comment by HelloWRC** [comment]
已修复。
