### ISSUE TITLE
导入.xlsx课程表失败

### ISSUE THREAD

**Issue by mmyes1145** [ClassIsland/ClassIsland#327]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

导入成功

### 实际结果

导入失败
![QQ20240914-121110](https://github.com/user-attachments/assets/164e2ae0-77e5-4903-9184-be3b511b7889)

![QQ20240914-120844](https://github.com/user-attachments/assets/2e7d0d72-e25f-4cc1-a860-9e7ad33bcbbc)

### 重现步骤

第一步打开档案编辑
第二步点击从表格导入
第三步导入表格

### 应用版本

1.5.0.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by mmyes1145** [comment]
win 11 23h2

**Comment by mmyes1145** [comment]
是微信自动把课程表转为只读才导致导入不进去
建议在导入失败页面加个请检查你的表格是否为只读

**Comment by mmyes1145** [comment]
是微信自动把课程表转为只读才导致导入不进去
建议在导入失败页面加个请检查你的表格是否为只读

**Comment by HelloWRC** [comment]
已修复。

**Comment by DryIce-cc** [comment]
虽然但是，为什么只读文件会打不开？
