### ISSUE TITLE
在设置里添加“以管理员身份运行”，让ClassIsland启动时提升权限

### ISSUE THREAD

**Issue by MKStoler4096** [ClassIsland/ClassIsland#330]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/zh-cn/latest/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/zh-cn/latest/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

置顶总失效，所以开了UiAccess，不得不用管理员身份运行，但是这样就无法直接开机启动了（开了UAC）

### 想要实现或优化的功能

给设置里面加个“以管理员身份运行”，让ClassIsland自己创建任务计划，在启动时进行调用，静默提升权限（跳过UAC）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
即使是从兼容性设置中打开“以管理员身份运行”也没用，故发此issue。

**Comment by liuziheng20091106** [comment]
似乎是兼容性设置的问题导致无法自启。
我用守护进程解决的（（（
顺便守护了一下音量，没30秒调100%（（（（

咳，扯远了。
任务计划跳过UAC很麻烦，不如直接声明管理员权限。
对于关闭UAC后的解决方法更简单，启动后现场申请管理员权限就行，即实现了自启，又不用担心兼容性。
说到守护进程，建议官方加一个，在某些情况下比较有必要。这个没法通过主程序（包括插件）来实现
最好的方法还是通过Windows服务来实现，UAC和守护进程一起解决，不过似乎这样后是以其他用户运行导致各种bug。
如果能用服务启动后再以当前用户身份运行就好了（有这个功夫不如弄守护进程）

上面写的有点乱，总结下来最好的方法是**启动后现场申请管理员权限**，最管用的方法是**守护进程**

**Comment by BH0721** [comment]
还有使用插件_在系统页面上显示主页面_时候，若设为管理员启动，无法自动启动

**Comment by HelloWRC** [comment]
目前已通过插件（https://github.com/ClassIsland/StartUpAsAdmin）实现本功能。
