### ISSUE TITLE
语段库，丰富的提醒

### ISSUE THREAD

**Issue by yingrenzhizhi** [ClassIsland/ClassIsland#331]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/zh-cn/latest/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/zh-cn/latest/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

每次看同一个上课提示略显枯燥，正好正值高三，每个人都被要求写给过我们班一个建议，但只是每天早上读一下，好句易忘。因此希望可给单一的提示付上一些生动。嘿嘿。

### 想要实现或优化的功能

首先引入一个 [语段档案] ，档案里可以添加列表 [语段集a] [语段集b] [语段集c] 等等。 每个语段集列表中可添加句子。
然后提醒部分的语言可用神秘代码来引用。引用可分多种模式引入，如按顺序引入，随机引入，倒序引入，只引入第 number 项 等等。
如提醒中填入文字   “即将上课，请做好准备。<yinru="语段集a",mode=1,shuju=1>"
其中 <yinru="语段集a",mode=1,shuju=1> 为神秘代码 ，yinru= 为引用的对象语段集列表 ，mode= 为引入的模式，shuju= 为附加数据，如 只引入第 number 项 的 number。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
感觉和以前的一堆issue有相似之处……
但是仍然是好的建议！

**Comment by MKStoler4096** [comment]
看起来是这样：

1. 让提醒文字支持变量添加；
2. 对提醒文字进行有条件的自动轮换。（偏向插件任务）

**Comment by liuziheng20091106** [comment]
https://github.com/ClassIsland/ClassIsland/issues/206 了解一下

**Comment by DryIce-cc** [comment]
类似 #206 中的「提醒组件化」，与之合并。
