### ISSUE TITLE
倒计时日的整体字体大小设置无效

### ISSUE THREAD

**Issue by 0623jmq** [ClassIsland/ClassIsland#335]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

可以单独调整距离XX还有(X天)的倒计时组件全部字体大小

### 实际结果

距离XX还有(X天)，仅能在组件设置内调整某部分大小，“距离”“还有”在高级设置中无法调整大小

### 重现步骤

在应用设置内的组件，选择倒计时日，再点击高级设置，里面的字体大小设置无效

### 应用版本

1.5.0.0(Codename Griseo)

### 操作系统版本

win10 22H2（操作系统内部版本19045.2788）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
已修复。
