### ISSUE TITLE
代码中未绑定字体大小的组件，组件特定字号设置无效。

### ISSUE THREAD

**Issue by DryIce-cc** [ClassIsland/ClassIsland#343]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

-

### 实际结果

-

### 重现步骤

「天气简报」「日期」组件的字体大小，仅跟随全局字体大小设定，组件高级设置中的字体大小调整无效。
这两个组件在代码中都没有指定使用 MainWindowBodyFontSize 字体大小。

### 应用版本

1.5.0.1-Griseo-02d5716(HEAD) (Core 1.4.0.0)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
理论上这些地方应该是使用默认字号，在组件范围内设置 TextElement.FontSizez 属性为 MainWindowBodyFontSize 应该可以解决。

**Comment by HelloWRC** [comment]
已修复。
