### ISSUE TITLE
「调试」时支持立刻结束当前的一切提醒内容

### ISSUE THREAD

**Issue by LyCecilion** [ClassIsland/ClassIsland#345]
我大抵是突然意识到右键菜单里，「清除全部提醒」那个按钮的作用了。实在抱歉让本人眼拙的能力从数学卷子上传染到了这里。<(_ _)>

不过我仍赞成干冰所言，提醒应当按照相对于提醒前后的时间而非持续时间显示。至于这一改进，暂且留给后续 issue 吧。

![Image_1723996498999.jpg](https://github.com/user-attachments/assets/9e2d449b-a9ea-4959-a464-a0915c7d5845)

---

### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/zh-cn/latest/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/zh-cn/latest/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

你正在调试 CI 的上下课提醒。你修改了它的时间偏移。现在它进入了长达 120s 的课前准备提醒。你发现它运作良好。随后，你想试试下课提醒，又修改了它的时间偏移，结果它的课前准备提醒还在不紧不慢地运行，即使它说，距离上课仅剩 0 秒。

![课前准备提醒](https://github.com/user-attachments/assets/8e80d0de-7a1f-4122-9e98-909da9ddf1bb)

你不解，继续修改着时间偏移，希望 CI 能快点退出课前准备提醒。然而，令你更不解的是，课前准备提醒仍然在继续——甚至当你尝试倒退时间的时候，它也在违背你的意愿。

![多少？](https://github.com/user-attachments/assets/4783053a-d3d6-4c23-8b65-8dae331c9d6a)

难道万物皆有灵性？你在心中暗想，但届时——物理课上的楞次定律，化学课上的勒夏特列原理和生物课上的负反馈调节突然敲击你的大脑。是的，当你闯下欲操控时间的祸患时，似乎这世间的一切，都在违背你的「非法」操作。

你长叹，点下 CI 的「停止主计时器」按钮，以为它终于会静止。然而课前准备提醒的进度条仍在进行。你想起了一段文字——

> 看似永不停息的时间，却和活动的画面组成影像一般，在它的最小刻度上静止，
>
> 但相对着观察者，静止却拥有了活动的性质，
>
> 归因是观察者的运动，还是观察者的静止，我们不得而知。

此，为「时钟悖论」。

### 想要实现或优化的功能

在「调试」页面加入一项新功能，强制结束当前正在进行或将要进行的一切提醒内容，刷新主界面。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
我觉得提醒处理方不去将结束时间转为提醒时长，而是计算当前处在开始时间和结束时间之间的位置，可能是更优雅的改进方法？

**Comment by LyCecilion** [comment]
> 我觉得提醒处理方不去将结束时间转为提醒时长，而是计算当前处在开始时间和结束时间之间的位置，可能是更优雅的改进方法？

支持这个想法 (●'◡'●)

**Comment by YiTTT-FlY** [comment]
调试恢复原来之后确实有这些现象，在编辑课表预览时遇到的bug

**Comment by MKStoler4096** [comment]
不是在提示存在时有一个“清除全部提醒”吗（）

**Comment by LyCecilion** [comment]
> ~~不是在提示存在时右键有一个“清除全部提醒”吗（）~~
> 
> 但是调试的时候结束一切提醒确实很实用（）

？？？？？我好像突然想起来的确有这么个按钮……Σ(ﾟдﾟ;)

**Comment by MKStoler4096** [comment]
> 不过我仍赞成干冰所言，提醒应当按照相对于提醒前后的时间而非持续时间显示。至于这一改进，暂且留给后续 issue 吧。

支持！比如提醒时改时间偏移……
