### ISSUE TITLE
想在大学使用ClassIsland

### ISSUE THREAD

**Issue by Dreamstarlake** [ClassIsland/ClassIsland#346]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/zh-cn/latest/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/zh-cn/latest/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

明年要考大学了，有点舍不得ClassIsland，想在大学继续使用。

### 想要实现或优化的功能

可以出一款适用于大学生的ClassIsland嘛？比如能够提醒大学专业课程授课时间和地点（据我所知，好像大学上课地点一直在变，没有固定教室），提前提醒学生上课之类的，最好有手机版和手表版吧，感觉要方便一点

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
有更优秀的 app。

**Comment by LyCecilion** [comment]
CI 本就只适合这种遵循固定模式的教学场景，想让 CI 兼容大学这种高灵活性的课表来说还是有点困难，并且也不是 CI 的开发初衷。

或许考虑 手机 / 手表 侧的 app 更加合适？例如鸿蒙端「一课表」。

![Screenshot_20240917_181834_com.example.course.jpg](https://github.com/user-attachments/assets/02582eec-df1c-444d-9a71-c4f106b28f97)

**Comment by Dreamstarlake** [comment]
哦，好的，一课表我也听说过，那行吧！
