### ISSUE TITLE
提供第三方下载方式

### ISSUE THREAD

**Issue by WHMyyds** [ClassIsland/ClassIsland#347]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/zh-cn/latest/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/zh-cn/latest/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

github网速有限，一时半会儿下不下来。但我觉得作为一个电教，在班级大屏公然翻墙好像不大合适，安个加速器软件也不算方便

### 想要实现或优化的功能

提供123云盘，蓝奏云，或[huang1111网盘](https://pan.huang1111.cn/).

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MF-Dust** [comment]
建议使用ghproxy

**Comment by MKStoler4096** [comment]
本来就有，只不过版本不是很新而已（）

这个要靠广大ClassIsland用户推广了（）

**Comment by WHMyyds** [comment]
好吧

**Comment by DryIce-cc** [comment]
宁要的是这个？
还以为是三个下载站都连不上，所以没办法更新呢…

**Comment by WHMyyds** [comment]
？你啥意思我没看懂

> 宁要的是这个？ 还以为是三个下载站都连不上，所以没办法更新呢…

**Comment by WHMyyds** [comment]
顺便bb一下，你们这种软件用mit不怕被一些企业套壳利用嘛

**Comment by DryIce-cc** [comment]
> @WHMyyds ？你啥意思我没看懂

镜像链接只能用来下载旧版本。如果要更新到最新版本，需要从 github ghproxy appcenter 中选一个来下载。在部分用户的网络环境下，这三个下载站都用不了。我以为阁下是后者，所以来提 issue 的。

> @WHMyyds 顺便bb一下，你们这种软件用mit不怕被一些企业套壳利用嘛

真想 *利用* 的话，许可证拦不住的（）
之前 wrc 有想法要申请软著之类的，目前也没什么进展。
不过就 ci 这个细分领域，资本应该看不上的说？

**Comment by MKStoler4096** [comment]
还真有三个都连接不上的*后者*（）
so在想是不是加一个自定义镜像源？

**Comment by WHMyyds** [comment]
是这样的。首先在不用vpn或加速工具的前提下，在班里能把github打开就是个奇迹。然后再在20个k不到的速度下下软件，下一个小时多不是问题...如果开发者们不想搞个镜像下载站的话我也不强求，我在家先下载好就是了

**Comment by MKStoler4096** [comment]
> 是这样的。首先在不用vpn或加速工具的前提下，在班里能把github打开就是个奇迹。然后再在20个k不到的速度下下软件，下一个小时多不是问题...如果开发者们不想搞个镜像下载站的话我也不强求，我在家先下载好就是了

找一个镜像站，比如github.akams.cn这样的下载不就好了吗……
然后更新用应用内置ghproxy镜像源基本没问题
~~（山东个别地方当我没说）~~

**Comment by LyCecilion** [comment]
> > 是这样的。首先在不用vpn或加速工具的前提下，在班里能把github打开就是个奇迹。然后再在20个k不到的速度下下软件，下一个小时多不是问题...如果开发者们不想搞个镜像下载站的话我也不强求，我在家先下载好就是了
> 
> 找一个镜像站，比如github.akams.cn这样的下载不就好了吗……
> 然后更新用应用内置ghproxy镜像源基本没问题
> ~~（山东个别地方当我没说）~~
> *原来我的issue有这个问题的……但是被flagged了*

ghproxy 在我这（IP 属地：陕西）也不稳定，经常连不上😢

**Comment by WHMyyds** [comment]
@MF-Dust 
https://hm6ds-my.sharepoint.com/:f:/g/personal/ban_hm6ds_onmicrosoft_com/Eup1xZ7vr2xJq77GGV2WB1MBO7pJ9Y1_aLukBDGt7qfskw?e=MH1gqe
我搞了个onedrive链接，密码ClassIsland，我设置的是所有人可以上传编辑
