### ISSUE TITLE
在 希沃白板 传屏界面时 无法在 最前方显示

### ISSUE THREAD

**Issue by XiaoDuoYa** [ClassIsland/ClassIsland#348]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

在进行 希沃白板传屏时，我希望ClassIsland课程表在 最前端显示（当我未设置 任何不在最前方显示的条件时，例如上课时不显示）

### 实际结果

在进行 希沃白板传屏时，ClassIsland课程表没有在 最前端显示，而是被遮挡

### 重现步骤

1. 首先，打开希沃白板5 Windows客户端（专业版，即不需要登录的版本，直接打开白板）
2. 连接平板或手机，进入传屏页面
3. 发现ClassIsland软件被希沃白板传屏页面遮挡。

### 应用版本

1.5.0.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
权限不足。需要在使用管理员权限运行 ClassIsland 的前提下，使用「UIAccess 提权」插件提升 UIAccess 令牌。
自启动参考 #319。

**Comment by wang-lu-yuan** [comment]
现在classisland无法在WPS所有窗口上置顶，已按照该解决方法操作，但无效

**Comment by MKStoler4096** [comment]
不可能（？）我这边测了，甚至不启用UIAccess都能置顶🤔

**Comment by DryIce-cc** [comment]
> 现在classisland无法在WPS所有窗口上置顶，已按照该解决方法操作，但无效

问下您的操作系统版本？
另外重新切换下窗口层级设定试试。
![image](https://github.com/user-attachments/assets/7ee1692d-0b90-4ab2-a60a-73f6c129c4f3)

**Comment by HelloWRC** [comment]
> 现在classisland无法在WPS所有窗口上置顶，已按照该解决方法操作，但无效

请提供复现此问题的录屏，以便于开发者确定问题

**Comment by Jack-tendy-538** [comment]
<img width="1639" height="848" alt="Image" src="https://github.com/user-attachments/assets/0903ac77-caaa-458e-83ce-d7169eaa2ad5" />
为什么我也不能置顶

**Comment by Mike-Luo-Leap** [comment]
并非。potplayer&wps ppt有时候也会遇到，而且是间歇性的

**Comment by farmer-snack** [comment]
其实可以开发一个Z序列
