### ISSUE TITLE
增加离线更新功能（从文件中更新）

### ISSUE THREAD

**Issue by Hansyang1129** [ClassIsland/ClassIsland#359]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/zh-cn/latest/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/zh-cn/latest/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

班级电脑无法连接上互联网（学校禁了），但仍想更新到最新版本
但现在只能将完整更新后的软件文件从老师电脑拷到班级电脑上，然后需要重新导入（加载）备份。

### 想要实现或优化的功能

在更新处可以添加"导出更新文件"和"从更新文件中更新"
并且尽量减小'更新文件'的体积以方便更新
这样就可以只用将'更新文件'从老师电脑拷到班级电脑，不需要重新拷贝'整个软件'以及重新导入（加载）备份

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
？
直接替换 ClassIsland.exe 就行

**Comment by Hansyang1129** [comment]
> ？ 直接替换 ClassIsland.exe 就行

ok
