### ISSUE TITLE
单独自定义提醒音效

### ISSUE THREAD

**Issue by 0623jmq** [ClassIsland/ClassIsland#366]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

可以准确播放自定义的 上课/放学/天气 提醒音效

### 实际结果

单独设置上课的自定义提醒音效，但是上课，下课(课间)，天气提醒音效都变成了和单独设置上课提醒音效一样，就是跟只能自定义一种提醒音效一样

### 重现步骤

应用设置-提醒-提醒提供方-上课提醒-高级设置-允许启用提醒音效-自定义提醒音效

### 应用版本

1.5.0.0(Codename Griseo)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
Note:「上课提醒」组合类别应该改名为「课程提醒」，或者被拆分以便于定义多个特殊高级设置。

**Comment by DryIce-cc** [comment]
与 #367 是同一个新功能，并不是 Bug。
