### ISSUE TITLE
希望可以双行或者同时运行两个

### ISSUE THREAD

**Issue by PrefacedCorg** [ClassIsland/ClassIsland#369]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

我是在zztek迁移过来的 因为zztek的作者迟迟不更新单双周（）
而我既需要显示课程表 也需要显示考试倒计时 就导致位置不够 调小了后排同学（我肯定不是坐最后面）又看不清
所以就需要两行来显示

### 想要实现或优化的功能

我目前的解决方案是使用沙盒运行两个 再使用向下便宜 但是沙盒难免会出现奇奇怪怪的bug
所以希望可以改为两行的

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
多行组件功能与 #181 重复

另外对于多开的请求，由于 ci 会使用管道与其它进程跨进程通信，多开会由于管道占用产生一些问题，所以多开的请求也不现实。
