### ISSUE TITLE
（在这里输入你的标题）小组件-文本无法使用

### ISSUE THREAD

**Issue by HUSX100** [ClassIsland/ClassIsland#381]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

当我在组件列表中添加了“文本”后，点击已添加的组件，应当出现对应的设置界面以及删除按钮

### 实际结果

点击已添加的“文本”组件，并没有出现相应的设置界面，也不显示“删除”按钮

### 重现步骤

安装了提权拓展，以管理员身份运行

### 应用版本

1.5.0.1

### 操作系统版本

22621

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
@HUSX100 上方先选择组件设置

**Comment by HelloWRC** [comment]
无法根据复现步骤复现此 Bug，请提供触发此 Bug 的录屏
