### ISSUE TITLE
临时课表上课倒计时结束弹出放学提醒

### ISSUE THREAD

**Issue by LCAleksei** [ClassIsland/ClassIsland#382]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/zh-cn/latest/app/faq/)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

正常使用临时课表

### 实际结果

启用临时课表，在第一节课（第二节课后关闭了放学提醒，第二节后面发生的事情未知）上课提醒（我开了上课提醒）结束后，弹出了放学提醒

### 重现步骤

1.加载临时课表
2.开启上课倒计时和放学提醒
3.等待第一节上课

### 应用版本

1.5.0.1

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
我目前无法根据重现步骤复现这个问题，把诊断数据导出一下看看
