### ISSUE TITLE
在时间表顶部变更一个“课间休息”为“上课”时，整个课程表会向前错位

### ISSUE THREAD

**Issue by jiangyin14** [ClassIsland/ClassIsland#387]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

在时间表的最开始多出一个未定义的课程，等待到“课表”进行定义

### 实际结果

所有课程表向前错位一格，将最后一节课的位置空出

### 重现步骤

在时间表的最开始放置一个“课间休息”，然后设置完课表后把其类型变更为“上课”

### 应用版本

1.5.0.1

### 操作系统版本

Windows 7 SP1 专业版 内部版本 7601

### 最后一步

- [X] #388

**Comment by jiangyin14** [comment]
建议将课程与时间表进行绑定，来避免这个问题。

**Comment by MKStoler4096** [comment]
~~好耶有人帮我报告了~~

其实在列表底部加一个早上的课程也会有这样的bug
