### ISSUE TITLE
【bug】自动时间偏移功能无效：即使功能处于开启状态并填写时间，每天仍然不会自动调整时间偏移

### ISSUE THREAD

**Issue by estocopy** [ClassIsland/ClassIsland#397]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [x] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

当开启此功能后，时间偏移会按照设定值每日自动调整增量

### 实际结果

开启此功能后，每天的时间偏移并不会被自动调整（就和没开一样）

### 重现步骤

打开这个功能，填写时间偏移量，等到第二天再打开设置看看，会发现时间偏移并未被调整

### 应用版本

1.5.0.1

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
概率问题（）

**Comment by DryIce-cc** [comment]
自动时间偏移只会在每次应用启动时调整。

**Comment by estocopy** [comment]
> 概率问题（）

可是我开了一周没有哪一天自动调整了的（

**Comment by estocopy** [comment]
> 概率问题（）

学校的时间每天都会有偏移，所以开了这个功能，结果没有一天不是自己调的（
