### ISSUE TITLE
【Bug反馈】1.5.0.2版本应用设置页面打开“外观”栏后，页面停止加载，重启CI后bug不再出现

### ISSUE THREAD

**Issue by luobo2333inGithub** [ClassIsland/ClassIsland#399]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

Windows11 专业工作站版 x64，1.5.0.2版本，应用设置页面，打开“外观”栏后，页面正常加载

### 实际结果

Windows11 专业工作站版 x64，1.5.0.2版本应用设置页面，打开“外观”栏后，设置页面UI停止加载，但其他按钮均可以正常点击。多次重启ClassIsland后bug会自动修复

### 重现步骤

1.使用微软源将软件版本从1.5.0.1升级到1.5.0.2
2.打开应用设置
3.点击“外观”选项卡（此时出现bug）
4.多次重启ClassIsland后bug会自动修复

### 应用版本

1.5.0.2

### 操作系统版本

Windows 11 x64 专业工作站版 23H2 （内部版本22631.4169）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
#172
