### ISSUE TITLE
通过机器识别智能上移 ClassIsland 主界面，以防遮挡屏幕内容

### ISSUE THREAD

**Issue by DryIce-cc** [ClassIsland/ClassIsland#412]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

【想法记录帖】
ClassIsland 主界面有时会遮挡课件等屏幕内容。

### 想要实现或优化的功能

通过离线机器识别 ClassIsland 主界面 所在区域的「文本」和「主体内容」，自动上移 ClassIsland 以防止遮挡屏幕内容。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by jiangyin14** [comment]
没啥用，如果害怕内容被遮挡可以选择设置规则让上课的时候不显示 也可以按需调节透明度

**Comment by LINQUQI** [comment]
大部分学校配的电脑配置并不完善使用机器识别等技术感觉不够轻量化，在配置较差的电脑上容易影响教学（PPT）的质量，带来卡顿与延迟，作为一个插件当然是可以的，但是否投入与回报不符呢
