### ISSUE TITLE
提醒导致当前窗口失去焦点

### ISSUE THREAD

**Issue by HUSX100** [ClassIsland/ClassIsland#417]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

当我正在前台放映 PPT 并使用翻页笔时，软件弹出上下课提示，该提示窗口获得焦点，当提示结束后，应当重新使正在放映的 PPT 获得焦点

### 实际结果

当提醒结束以后，焦点仍然保持在 Classisland 上，使得翻页笔的翻页指令无法正确输入至 PPT 放映窗口，导致翻页笔无法正常使用

### 重现步骤

使用管理员权限运行并安装 UIAccess 插件
设置软件主窗口置底，但是提醒设置为置顶

### 应用版本

1.0.5.2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
关于失去焦点的 https://github.com/ClassIsland/ClassIsland/labels/Bug ：
这个与置顶需要激活窗口有关，应该是没有办法修复。
只能不建议设置软件主窗口置底，可以使用隐藏窗口等代替。

> [!note]
> 「**当提示结束后，应当重新使正在放映的 PPT 获得焦点**」是一个 https://github.com/ClassIsland/ClassIsland/labels/%E5%8A%9F%E8%83%BD%E4%BC%98%E5%8C%96 。

**Comment by HUSX100** [comment]
能否在提醒之前先获取当前的台前窗口，提醒显示完之后再将焦点转移到原窗口
