### ISSUE TITLE
设备异常关闭后，软件所有信息被重置

### ISSUE THREAD

**Issue by ZhiZaiDuoFang** [ClassIsland/ClassIsland#421]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

由于学校电力系统故障，希沃常突然断电而关机，ClassIsLand常在运行时被突然关闭。重启之后，软件应如平常一般正常运行，显示当前课程并提醒上课。

### 实际结果

重新开启希沃后，ClassIsland显示设置向导，ui设置、课程设置等全部丢失，重置为初始状态。

### 重现步骤

1.在电脑上运行ClassIsland。
2.保存您的所有文件。
3.直接将设备断电（有硬盘损坏风险）。
4.重启设备。
5.有概率重现上述状况（如图所示）。
![屏幕截图 2024-10-12 130949](https://github.com/user-attachments/assets/5126ca9b-e660-46b3-8f85-d5ba7b3ad65a)

### 应用版本

1.5.0.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
意外断电情况确实会导致 ClassIsland  的一部分文件损坏，这很难完全避免。不过应用默认情况下会自动定期备份您的配置文件，您可以按照 [文档](https://docs.classisland.tech/app/backup.html#%E6%81%A2%E5%A4%8D%E5%A4%87%E4%BB%BD) 的指南恢复备份的配置文件。
