### ISSUE TITLE
科目中设置不“启用下课提醒”无效

### ISSUE THREAD

**Issue by MKStoler4096** [ClassIsland/ClassIsland#427]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

不提醒

### 实际结果

科目中设置不“启用下课提醒”无效

### 重现步骤

1. 科目中设置不“启用下课提醒”
2. 触发下课提醒

### 堆栈跟踪（可选）

```shell
无
```

### 应用版本

1.5.0.3-Griseo-af0cf67(HEAD) (Core 1.4.0.0)

### 操作系统版本

10.0.26100

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
下课提醒只会从当前的下课时间点获取附加设置，所以在科目上设置下课提醒附加设置没法影响下课设置

**Comment by MKStoler4096** [comment]
@HelloWRC 那应该把这个功能加上吧，或者一出这个选项（）
