### ISSUE TITLE
剩余时间显示错误

### ISSUE THREAD

**Issue by wo-jia-de-hei-dan** [ClassIsland/ClassIsland#430]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

时间显示正常

### 实际结果

<img width="260" alt="批注 2024-10-16 113241" src="https://github.com/user-attachments/assets/d1945f1b-abdf-40af-b2f2-2dc6f9bf5764">

### 重现步骤

![image](https://github.com/user-attachments/assets/1cbc7a42-774e-493b-9780-8f3afdd6c080)

### 应用版本

1.5.0.3

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
https://github.com/ClassIsland/ClassIsland/commit/589d6991e8b3d34cfce0a43c773c6f4c686ad1f9#diff-6fe567ee81f97e4c928a937fafb8352edf6af4ba22c6eb9fd1610d4c88fb86f4R26
这里不知道为什么从 .Minutes 改用 .TotalMinutes 了，感觉原来的好看一点🤔

**Comment by DryIce-cc** [comment]
https://github.com/ClassIsland/ClassIsland/commit/589d6991e8b3d34cfce0a43c773c6f4c686ad1f9#diff-6fe567ee81f97e4c928a937fafb8352edf6af4ba22c6eb9fd1610d4c88fb86f4R26
这里不知道为什么从 .Minutes 改用 .TotalMinutes 了，感觉原来的好看一点🤔
