### ISSUE TITLE
（在这里输入你的标题）关于换课

### ISSUE THREAD

**Issue by Human-air** [ClassIsland/ClassIsland#432]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

班主任在周三通知本周四的课程需要调整，我希望能在周三提前预定调整后的课程，但目前的版本不支持提前预定更改课程安排。
此外，此次换课涉及到周五的体育课和周四的化学、生物课，但现有版本无法将课程调整到当天以外的其他日期。

### 想要实现或优化的功能

1.课程调整预定功能：希望系统能够支持提前预定和修改未来几天的课程安排，以便在班主任通知变动时，能够迅速更新到课表中，避免忘记要调整的课程有哪些
2.跨日期的课程调整功能：希望系统能够支持将课程调整到当天以外的其他日期，比如将周五的某个课程与周四的某个课程进行对调，更灵活地应对课程调整需求。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
与 #321 重复
