### ISSUE TITLE
添加学生表功能

### ISSUE THREAD

**Issue by LongqisongDuo** [ClassIsland/ClassIsland#438]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

我想做一些插件，需要用学生表

### 想要实现或优化的功能

![微信图片_20241019225614](https://github.com/user-attachments/assets/55ab3ea0-9ebb-4495-af40-6b4887f17699)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
- [ ] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为灵动课表的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project/)来实现特殊的需求）。

**Comment by jiangyin14** [comment]
不符合灵动课表定义，与软件设计理念严重相悖。
建议使用其他软件，或用插件实现。

**Comment by jiangyin14** [comment]
@LongqisongDuo 
是否方便加入官方QQ讨论组？方法具体参看readme/docs

**Comment by LongqisongDuo** [comment]
> 不符合灵动课表定义，与软件设计理念严重相悖。 建议使用其他软件，或用插件实现。

可以使用插件吗？我表示怀疑。

**Comment by LongqisongDuo** [comment]
> @LongqisongDuo 是否方便加入官方QQ讨论组？方法具体参看readme/docs

我没有QQ

**Comment by bywhite0** [comment]
理论上可以通过编写插件另外存放这个学生表档案

**Comment by jiangyin14** [comment]
实际上讨论这个问题没有意义。往ClassIsland内集成学生相关功能是为了做什么？随机点名吗？优秀的设计也有很多，给ClassIsland添加这个功能实际上没什么意义，而且不好设计触发

**Comment by undefftr** [comment]
> 实际上讨论这个问题没有意义。往ClassIsland内集成学生相关功能是为了做什么？随机点名吗？优秀的设计也有很多，给ClassIsland添加这个功能实际上没什么意义，而且不好设计触发

我同意，
icc是你无法想象的好用的（

**Comment by DryIce-cc** [comment]
@LongqisongDuo
「**我想做一些插件，需要用学生表**」这个动机并没有什么意义。

设计功能固然简单，但一项功能的开发需要开发者付出时间精力。
**ClassIsland** 的开发者都是自发的付出，都伴有学业压力。
我们需要知道一项功能的实现会有什么价值，了解大部分用户想要的是什么，才能够将时间分配到开发这项功能上。
