### ISSUE TITLE
可以恢复已清除的提醒

### ISSUE THREAD

**Issue by LongqisongDuo** [ClassIsland/ClassIsland#442]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

为了有时候我清除了提醒想恢复，但是没有这个功能

### 想要实现或优化的功能

![微信图片_20241019225628](https://github.com/user-attachments/assets/d5e6209a-0eac-4e38-979a-5d5f016019f2)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by liuziheng20091106** [comment]
在校学习要认真，不能老想着ci哦~

恢复全部提醒太抽象了，建议改成重播上一次触发的提醒（保存上次触发器绑定的提醒）这样类似于历史记录而不仅是恢复清除掉的提醒。

另，可以顺便写一个推迟下一次提醒

**Comment by DryIce-cc** [comment]
这个实现起来其实不是很现实🤔

**Comment by Griseo-bh3rd** [comment]
感觉实用性不大，如果需要恢复提醒可以手动重启ci，而且这种清除提醒后恢复的需求真不大

**Comment by HelloWRC** [comment]
> 感觉实用性不大，如果需要恢复准备上课提醒可以手动重启ci，而且这种清除提醒后恢复的需求真不大

+1

并且考虑到提醒服务架构限制，这个功能实现起来也不太现实。
