### ISSUE TITLE
希望能增加考试模式

### ISSUE THREAD

**Issue by baoliaojiang** [ClassIsland/ClassIsland#444]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

学校中除了上课，偶尔还会举行月考、期中考、模拟考、期末考等考试. 在此期间并不会使用到课程表，但大多数监考老师并不会关闭Classisland软件，并且也不会提供考试倒计时，这很影响考生作答.

### 想要实现或优化的功能

希望能新增考试模式.具体如下:
1.支持在别的设备上设置考试科目（可能不止一天）及考试时间，并可复制文件，在其他安装有Classisland的设备中直接使用。
2.考试期间，默认全屏显示考试信息（考试科目、考试时间等）及倒计时，并且每隔一段时间（如30min）为考试进行语音播放提醒（该功能可关闭可开启，语音播放示例:各位考生请注意，距离考试结束还剩xxmin，请抓紧时间作答）及考试开始提醒（示例:各位考生请注意，考试开始）、考试结束提醒（示例:各位考生请注意，考试结束，请放下笔停止填写试卷及答题卡，收卷），并在考试最后10min、5min单独再提醒一遍。若因其他考试原因需要取消全屏时，缩小至原本课程表位置及大小，点按附近按钮恢复全屏。（可参考希沃白板5全屏倒计时及图）
3.各科考试之间过渡时间（倒计时）亦可设置，并在前一科目考试结束提醒下一科目考试信息（若示例:下一考试科目为xx，考试时间xxmin，请考生抓紧时间复习，做好考试准备。）并在考试前3-5分钟进行考试准备，提醒考生进入考场。

全屏可参考 ![IMG_20241020_122722](https://github.com/user-attachments/assets/948dabfb-c063-4b50-9dfc-211152ad6de5)

大概就这些吧……如果实现不了我就再研究下插件怎么写。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by jiangyin14** [comment]
这个需求快重复重炸了，麻烦下次真的先搜一下相关issue
可以去用DSZ-exam-showboard

**Comment by bywhite0** [comment]
似乎与#314 重复
