### ISSUE TITLE
灵动岛组件字体统一设置

### ISSUE THREAD

**Issue by WHMyyds** [ClassIsland/ClassIsland#448]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

我在调字体时发现每个组件字体都得挨个调，非常麻烦

### 想要实现或优化的功能

在组件模块加一个字体大小全局设置的功能（最近提的issue有点多，开发大佬们麻烦你们了）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
在【外观】设置里面
![image](https://github.com/user-attachments/assets/8849c269-309c-46b8-a6ba-4dc599021bbc)

**Comment by WHMyyds** [comment]
没用。。。
比如说改了后，倒计时的字体还是那样

**Comment by DryIce-cc** [comment]
> 没用。。。 比如说改了后，倒计时的字体还是那样

你指的是「倒计时日」组件吗？
“距离”“还有”是正文字体大小。
带颜色字体大小须在「组件设置」滑块中调整。
如果还是不行，请确认 ClassIsland 版本为最新，并提供录屏和诊断数据。

**Comment by WHMyyds** [comment]
那这个issue到此为止吧
