### ISSUE TITLE
有时''档案设置''窗口无法关闭

### ISSUE THREAD

**Issue by WHMyyds** [ClassIsland/ClassIsland#449]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

右上角显示最大化，最小化，关闭按钮

### 实际结果

有时（大概每十次有一次）不显示右上角窗口控制图标

### 重现步骤

1.打开classland托盘图标
2.点档案设置
3.关闭按钮没了！

### 应用版本

1.5.0.3

### 操作系统版本

1903（被希沃爆改版

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
注意下方标语，点击窗口中别处切换焦点即可关闭窗口。
![image](https://github.com/user-attachments/assets/310c6b80-5a70-4bcd-829d-0df0b5e65642)

**Comment by WHMyyds** [comment]
点了，没用。
是因为触屏的原因吗？我们班没键鼠

**Comment by HelloWRC** [comment]
> 点了，没用。
> 是因为触屏的原因吗？我们班没键鼠

可以提供下录屏吗

**Comment by bywhite0** [comment]
这边用本地 PC(22H2) 尝试了一下，触摸屏需要点击两次才能切换焦点

**Comment by WHMyyds** [comment]
> 可以提供下录屏吗
抱歉，不能，我不是电教
主要是一打开就没那三个按钮
