### ISSUE TITLE
「课程表」组件在显示明天课表时，不能随临时课表的启用或切换而自动更新

### ISSUE THREAD

**Issue by LyCecilion** [ClassIsland/ClassIsland#450]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

显示明天课表的「课程表」组件，应当随临时课表的启用或切换而自动更新。

### 实际结果

与期望相反。在切换临时课表时，「课程表」组件并未自动更新。

### 重现步骤

![QQ_1729438897549](https://github.com/user-attachments/assets/dba0f021-0256-42f8-81aa-fda529992954)

确保已经设置了组件「课程表」，且开启了显示明天课表的功能。「放学后显示」（放学状态下）和「总是显示」均可触发此问题。

![QQ_1729438959978](https://github.com/user-attachments/assets/7e381d81-8d5d-4be4-a518-79ef3fa6d74b)

任意切换临时课表，注意到明天课表并未随之变化。

### 应用版本

1.5.1.0 (Codename Himeko)

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by Griseo-bh3rd** [comment]
不合理吧。。。。比如你周日补周五然后周一正常上，按你的意思是显示周六的？

**Comment by DryIce-cc** [comment]
注意到明日课表与临时课表无关（）
https://github.com/ClassIsland/ClassIsland/issues/450#issuecomment-2428658394
帮零音关一下 w

**Comment by LyCecilion** [comment]
> 不合理吧。。。。比如你周日补周五然后周一正常上，按你的意思是显示周六的？

@Griseo-bh3rd 哎？！(๑>_<๑)

感谢更正。你这么一说提醒我了，我也忘了当初我是出于一个什么心理而提的这个 issue……

> 好像是当时切换临时课表的时候看见上面的明天课表完全没动，所以就以为是 CI 这个组件出了不会自动更新的 bug（小声）

😭😭😭😭😭铸币了，真正铸币了
