### ISSUE TITLE
优化“放学提醒”逻辑

### ISSUE THREAD

**Issue by wang-lu-yuan** [ClassIsland/ClassIsland#454]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3A新功能) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project/)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

现有的“放学提醒”逻辑仍然无法满足实际需要

### 想要实现或优化的功能

将“放学”作为时间点添加，
当某个放学时间点后距离下一个“上课”类型或“课间休息”类型时间点时长≤5min，保存（或关闭编辑窗口）时弹出提示：检测到有“放学”时间点后有课程/课间休息，是否检查？
 - 点击“是”，自动选择对应的“放学”时间点；
 - 点击“否”，保存（或关闭页面）。

当某个时间表中没有添加任何“放学”类型时间点时，保存（或关闭编辑窗口）时弹出提示：检测到未添加至少一个“放学”时间点，是否自动添加？
 - 点击“是”，自动在时间表末尾添加一个“放学”类型时间点；
 - 点击“否”，保存（或关闭窗口）
 - 点击“我自己检查”，关闭提示。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by Griseo-bh3rd** [comment]
与 #392 实质重复
