### ISSUE TITLE
应用设置 > 调试 > 特性调试窗口 发生崩溃

### ISSUE THREAD

**Issue by LyCecilion** [ClassIsland/ClassIsland#455]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

不应崩溃。(^_^)

### 实际结果

崩溃啦！(T_T)

### 重现步骤

注意到，打开应用设置后，在「调试」选项卡中点击「特性调试窗口」，即触发崩溃。 

![image](https://github.com/user-attachments/assets/cd40960d-072a-4874-8fc0-4ade9b26a923)

若选择「忽略错误，强制继续运行」，则可以打开目标窗口。

### 堆栈跟踪（可选）

```shell
System.Windows.ResourceReferenceKeyNotFoundException: 未找到“LessonsListBoxItemTemplateMultiConverter”资源。
   at MS.Internal.Helper.FindResourceHelper.DoTryCatchWhen(Object arg)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
```

### 应用版本

1.5.1.0-Himeko-ace5031(HEAD) (Core 1.4.0.0)

### 操作系统版本

10.0.26100.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
疑似课程表组件不存在并无课程就会这样：
![image](https://github.com/user-attachments/assets/2bcceb63-45e5-4fd2-ab65-1bcc45a4fca4)
这里的课表没了（）

**Comment by Griseo-bh3rd** [comment]
确认仅出现在最新测试版

**Comment by Griseo-bh3rd** [comment]
貌似是 3f6a4a1 的问题？

**Comment by DryIce-cc** [comment]
> 貌似是 [3f6a4a1](https://github.com/ClassIsland/ClassIsland/commit/3f6a4a111111a8a80209469cab79e300b8ab093e) 的问题？ edit: revert之后不崩了

淦，怎么又是我写的bug……

**Comment by DryIce-cc** [comment]
emm？
`1.5.1.0-Himeko-ace5031(dev) (Core 1.4.0.0)` 未能复现

> @MKStoler4096 这里的课表没了

我这里测试，只有今天没有课程/未加载课表会显示为空白，理论上是正常的，也没有报错

**Comment by Griseo-bh3rd** [comment]
> emm？ `1.5.1.0-Himeko-ace5031(dev) (Core 1.4.0.0)` 未能复现
> 
> > @MKStoler4096 这里的课表没了
> 
> 我这里测试，只有今天没有课程/未加载课表会显示为空白，理论上是正常的，也没有报错

？我这里测试分支强制更新到最新版稳定复现

**Comment by HelloWRC** [comment]
> 疑似课程表组件不存在并无课程就会这样： ![image](https://private-user-images.githubusercontent.com/178344462/379482728-2bcceb63-45e5-4fd2-ab65-1bcc45a4fca4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjAyNDQsIm5iZiI6MTcyOTg1OTk0NCwicGF0aCI6Ii8xNzgzNDQ0NjIvMzc5NDgyNzI4LTJiY2NlYjYzLTQ1ZTUtNGZkMi1hYjY1LTFiY2M0NWE0ZmNhNC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxMjM5MDRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZDA3MTA2MzdjOGJiNzQ5YWIyYWVmYjNmZDY1MmU3MTBlZjU2YTY1NzZmZjY1ODRkMDI0NmQzMzc1MzFiOTA5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.gDpVO_gmmA4bM-JTICiAnul5q5d0d6gEXhnhsLsR_W8) 这里的课表没了（）

没有课程这里当然是空的，无课程占位文本不是由 `LessonsListBox` 呈现的，而是由课表组件自己呈现的。
