### ISSUE TITLE
在WPS中无法置顶

### ISSUE THREAD

**Issue by wang-lu-yuan** [ClassIsland/ClassIsland#468]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

正常置顶

### 实际结果

没有置顶

### 重现步骤

不需要触发，另，复现视频会在ClassIsland官方群发布

### 应用版本

1.5.0.3

### 操作系统版本

Windows 10 Professional 22H2 内部版本19045.2965

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
是否尝试过 UiAccess 插件？没有的话试一下再以管理员身份重启 ci。

**Comment by wang-lu-yuan** [comment]
> 是否尝试过 UiAccess 插件？没有的话试一下再以管理员身份重启 ci。

看了视频你就知道，我开了uiaccess并且正常工作

**Comment by wang-lu-yuan** [comment]
> 按照录屏内的方法无法复现这个问题，请导出您的诊断信息以便于开发者进一步诊断问题。

已解决问题，原因如图所示![SharedScreenshot.jpg](https://github.com/user-attachments/assets/c924a8fc-c4d4-4fdc-89af-b70da45d612a)

@HelloWRC
