### ISSUE TITLE
主界面无法置于教学软件【易教学助手】的白板界面之上

### ISSUE THREAD

**Issue by WindDrift** [ClassIsland/ClassIsland#469]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

在【易教学助手】的白板界面中正常显示主界面。

### 实际结果

【易教学助手】的白板界面显示在主界面之上，即使已在应用设置更改窗口层级为`置顶`，且未启用任何会使主界面隐藏的设置项。
值得一提的是，全屏强调特效会正常显示在白板界面之上，但提醒出现时主界面仍然无法显示在白板界面之上。
还值得一提的是，在使用【实物展台】（按钮在白板左边）时，主界面会显示在实物展台界面之上。

### 重现步骤

0. 运行[【易教学助手】（测试版本为 v1.20.2 ）](https://www.hik-cloud.com/teach-prepare-web/download.html#/download)；
1. 点击底部【易教学助手】工具栏的【白板】，进入白板界面；
![image](https://github.com/user-attachments/assets/d28374cb-52e3-4c5b-8697-94209f5005f8)
2. 如图，白板界面显示在主界面之上。
![image](https://github.com/user-attachments/assets/9d99f2a6-3d4f-48a9-ae06-c35c3baf9cf9)

### 应用版本

1.5.1.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by jiangyin14** [comment]
请认真阅读FAQ。
是否尝试过安装UIACCESS提权插件？这一插件可帮助 ``` ClassIsland 主窗口 ``` 具有更高的优先级，也许能解决问题。

**Comment by WindDrift** [comment]
> 请认真阅读FAQ。 是否尝试过安装UIACCESS提权插件？这一插件可帮助 `ClassIsland 主窗口` 具有更高的优先级，也许能解决问题。

安装 [UIAccess](https://github.com/HelloWRC/GrantUiAccess) 插件后问题已解决，感谢回复~此 Issue 将以完成状态关闭。
