### ISSUE TITLE
提醒在希沃白板上有时不能置顶

### ISSUE THREAD

**Issue by HUSX100** [ClassIsland/ClassIsland#471]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

当下课时，提醒应当置顶显示

### 实际结果

当前台窗口是希沃白板 5 时，下课时提醒有时不能置顶

### 重现步骤

1.开启提醒的置顶功能
2.管理员模式运行并安装 UIAccess
3.打开希沃白板

### 应用版本

1.5.1.0

### 操作系统版本

22621

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
没法复现……？

**Comment by Griseo-bh3rd** [comment]
无法复现

**Comment by HelloWRC** [comment]
目前我还没遇到过这个问题，如果有其他遇到过这个问题的用户，可以在这里分享更多信息以助于开发者诊断问题。

**Comment by MKStoler4096** [comment]
是不是插件没有加载成功？我倒遇见过这种问题（）
