### ISSUE TITLE
classisland.tech域名证书过期

### ISSUE THREAD

**Issue by zhoucAndrew** [ClassIsland/ClassIsland#479]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

正常访问官方网页

### 实际结果

返回net::ERR_CERT_DATE_INVALID报错
证书信息：![image](https://github.com/user-attachments/assets/031a4ca2-0165-46f3-88ef-d3916352297b)

### 重现步骤

1.使用Chrome浏览器的标准防护
2.访问classisland.tech
3.问题重现
![image](https://github.com/user-attachments/assets/a0568b76-09dc-43af-8ab3-260df6491c62)

### 应用版本

非ClassIsland客户端故障

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
已处理完毕。
