### ISSUE TITLE
在Windows10LTSC中无法调用EdgeTTS（与#163相似）

### ISSUE THREAD

**Issue by Liuziyi2013** [ClassIsland/ClassIsland#489]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

能够正常调用EdgeTTS

### 实际结果

将EdgeTTS设为TTS引擎后没有效果

### 重现步骤

1.使用Win10教育版LTSC
2.将EdgeTTS作为TTS引擎

### 应用版本

1.6 Himeko

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by LyCecilion** [comment]
零音教室的白板和零音自己的笔记本都无法使用 EdgeTTS，看样子不是零音一个人的问题了

**Comment by MKStoler4096** [comment]
现在所有C#项目都没法使用EdgeTTS，看起来不是CI的锅

**Comment by MKStoler4096** [comment]
y，LTSC2019和LTSB2016都是这样

**Comment by HelloWRC** [comment]
这个问题可能是 edgetts 相关 api 的调用方式发生了一些变化，使 ci 目前使用的 Edgetts 库无法使用导致的。

**Comment by HelloWRC** [comment]
目前有 NuGet 包（https://www.nuget.org/packages/EdgeTTS.Framework）实现了修改后的接口，但目前版本的 edgetts 的接口对中国大陆地区的 ip 进行了一些限制 <https://github.com/rany2/edge-tts/issues/290>，需要添加额外的加密参数。
