### ISSUE TITLE
可选隐藏托盘图标

### ISSUE THREAD

**Issue by bywhite0** [ClassIsland/ClassIsland#495]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=-label%3ABug) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

由于班上总有小鬼喜欢乱按托盘，导致CI经常被无故退出或者被恶意隐藏（

### 想要实现或优化的功能

在设置中添加「隐藏托盘图标」的选项，由于可以使用URL打开设置，因此不需要更改其他（能进应用设置）的逻辑。

不过可以在重复实例对话框中添加一个「打开应用设置」的按钮？

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by wang-lu-yuan** [comment]
这样在某些条件下无法确认ClassIsland的工作状态，所以最好能设置快捷键

**Comment by HelloWRC** [comment]
感觉可以考虑下 #311 这种直接锁住相关功能的方式，直接隐藏图标感觉不是很好。

**Comment by bywhite0** [comment]
> 感觉可以考虑下 #311 这种直接锁住相关功能的方式，直接隐藏图标感觉不是很好。

这个可以有，另外可以在锁定时使托盘图标单击行为失效，避免误触。

**Comment by MKStoler4096** [comment]
头一回看见Github仓库要续火的……

> > 感觉可以考虑下 #311 这种直接锁住相关功能的方式，直接隐藏图标感觉不是很好。
> 
> 这个可以有，另外可以在锁定时使托盘图标单击行为失效，避免误触。

这不原作者反映了吗，一处待沟通吧（）
