### ISSUE TITLE
创建临时层导致课表功能失效

### ISSUE THREAD

**Issue by HUSX100** [ClassIsland/ClassIsland#499]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

当我创建临时层后，课表应当显示临时层，并且正常按照临时层课程进行通知

### 实际结果

当我创建完临时层之后，课表可以正常加载，但是提醒等功能将会全部失效

### 重现步骤

1.创建并应用临时层（使用与当前不一样的时间表）
2.更改临时层的课程
3.提醒等功能失效，也不会显示当前活动状态
4.重启软件后方可恢复正常

### 应用版本

1.5.1.0

### 操作系统版本

22621

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
无法根据您的描述复现这个问题，可以上传一下复现录屏和诊断信息吗
