### ISSUE TITLE
轮播组件最小长度

### ISSUE THREAD

**Issue by FrankXiDong** [ClassIsland/ClassIsland#501]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=-label%3ABug) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

尝试了轮播组件，发现由于轮播的各个组件长度不一，CI灵动岛的长短时不时发生变化，会显得很烦（误）

### 想要实现或优化的功能

给轮播组件设置一个最短长度，如：
设置最短长度为10。
若当前子组件长度为8，该轮播组件占位长度依旧为10，当前子组件在轮播组件中居中显示。
若当前子组件长度为12，该轮播组件占位长度为12。

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by HelloWRC** [comment]
已实现。
