### ISSUE TITLE
功能请求：内置提示音

### ISSUE THREAD

**Issue by dream-pep** [ClassIsland/ClassIsland#512]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=-label%3ABug) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

每次拷贝到别的班级，自定义音效都会失效

### 想要实现或优化的功能

自带预设提示音

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by bywhite0** [comment]
自定义音效不也得把音频文件一并拷过去吗（

**Comment by YiTTT-FlY** [comment]
> 自定义音效不也得把音频文件一并拷过去吗（

他应该想说，他设置了自定义音效，文件也拷进去了。但是复制软件给其他班设置就不能定位音频文件，要重新定位。我也遇到了，每次复制覆盖后要重新定位一次。也是希望优化自动定位本文件夹的音频文件（我一般放classisland beta 文件夹里面）

**Comment by HelloWRC** [comment]
> 每次拷贝到别的班级，自定义音效都会失效

可以考虑把自定义的提示音放在应用目录下，然后使用相对路径引用。

**Comment by wang-lu-yuan** [comment]
> （我一般放classisland beta 文件夹里面）
应当是´data´吧？看着有点奇怪

**Comment by YiTTT-FlY** [comment]
> > （我一般放classisland beta 文件夹里面）
> 
> 应当是`data`吧？看着有点奇怪
> 

beta版啊，公测版，所以是bata文件夹（捂脸）

**Comment by Griseo-bh3rd** [comment]
啊？开始投票的还要保活啊？
