### ISSUE TITLE
天气提醒提供的天气地区不全

### ISSUE THREAD

**Issue by AtriDayo** [ClassIsland/ClassIsland#518]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

在深圳等地区可以正常选择区域（南山区，宝安区等）

### 实际结果

只能选择深圳整体，无法准确选择到区域

### 重现步骤

在设置中找到天气栏，选择区域，找到深圳

### 应用版本

1.5.0.4

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
小米天气就这么个lj玩意……见 #325 #168。

**Comment by bywhite0** [comment]
`xiaomi_weather.db` 缺少维护导致的，小米天气应用已经可以选择了。![Screenshot_2024_1120_121253.png](https://github.com/user-attachments/assets/1e2e6a17-40e3-44c9-8e40-ed5fee66a737)

> 小米天气版本: 16.0.3.5

**Comment by HelloWRC** [comment]
#548 引入了通过小米天气 API 搜索城市的功能，应该可以解决这个问题。
