### ISSUE TITLE
功能沙盒（自动修复运行中的异常而不是崩溃）

### ISSUE THREAD

**Issue by liuziheng20091106** [ClassIsland/ClassIsland#519]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=-label%3ABug) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

事实上，由于“轮换组件”“自动化”等功能的添加，部分插件或功能的逻辑缺陷会被大幅度放大，造成包括但不限于**内存泄露**，**程序错误**，**操作卡顿**等问题，这时候就需要我们抄袭Chrome的著名的_沙盒_机制了！
功能沙盒与浏览器的沙盒是有所不同的，我们并不需要浏览器沙盒所具有的安全性机制，也没必要弄复杂的管理机制。

### 想要实现或优化的功能

将每个功能放在独立的沙盒中运行（可以理解为子进程）由管理层负责沙盒的加载，运行，交互，监测，异常处理。
> 这就像如果一个程序出问题了，我们可以用任务管理器来终结他;如果Windows出问题了，winload会蓝屏显示错误并让系统停止运行

>又比如，classisalnd崩溃不会引起Windows崩溃我们可以在不重启Windows的前提下重新打开classisland（这个总看得懂吧）。我们的目标是让ci的部分组件出现异常时程序可以自动终止对应功能，并将其重启。

程序结构可以参考这个
```
-Classisland.exe
   -检测器（监测主进程是否有异常行为）
   -监视器1
      -设置界面
      -档案管理
      -灵动岛
      -天气服务
      -主题色服务
      -提醒
      -TTS
   监视器2
      -插件1
      -插件2
      ......
   -子监视器-灵动岛
      -灵动岛组件1
      -灵动岛组件2
   -监视器3
      -子监视器-自动化任务1
           -第一个行动
```
如果**检测器**发现内存超过上限，那就向所有**一级监视器**发送检测命令。
如果“监视器2”负责区域内存占用过高，那就检测具体是哪个子进程的问题件。
如果“插件2”占用内存过高，那就寻找是否有“子监视器”如果有则任务不断向下传递。
如果没有子监视器，那就重新加载定位到的问题组件。
（一般来说重启足以解决大部分问题，如果出现问题频率过高，则自动禁用对应组价）

实际操作∶
内存占用过高-灵动岛内存过高-组件2内存占用过高（组件2属于插件）-尝试重新加载组件，内存没有明显减少-尝试停用组件，内存没有明显减少-尝试停用对应插件，内存大幅度降低-报告问题解决。

内存占用过高-灵动岛内存占用过高-没有组件异常-重启灵动岛部分程序-灵动岛内存占用任然高-报告问题解决失败，停止灵动岛运行，弹出崩溃弹窗（选择十分以无灵动岛状态运行）

内存占用过高-主题色服务内存占用过高-......-停用主题色提取timer-报告问题解决
当然就算沙盒机制能阻止整体崩溃，但任然不是修复问题的长久之道。要根本解决问题，需要解决对应问题而不是不断的重启。

沙盒运行过程应记录日志，并且优先级为警告。
沙盒一旦被触发，应该通过appcenter上传错误问题，同种问题在改变设置前仅上传一次。
沙盒可以被调试
沙盒可以热更新（?）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
工作量恐怕……？

**Comment by liuziheng20091106** [comment]
> 工作量恐怕……？

事实上现在ci也有沙盒的代码，只是还没把它独立出来。
比如，安装插件后如果插件报错并不会引起ci退出，你可以在插件页面看到“遇到错误”“错误信息”标签。这也是一种功能性隔离
