### ISSUE TITLE
预加载

### ISSUE THREAD

**Issue by liuziheng20091106** [ClassIsland/ClassIsland#521]
### 背景与动机

希沃没有给你的电脑配置14900kf和4090ti显卡，所以每次播放提醒总会卡卡卡卡卡卡......

经过测试，导致卡的主要原因是4k电脑提取屏幕\壁纸主题色占用的cpu资源过高，次要原因是水波纹渲染和语音合成请求。
只需要提前合成语音并准备好播放（加载进内存里），并且在必要时候禁用主题色提取timer即可
当然禁用天气刷新，组件轮换等占用资源较大的服务可能也会在一定程度上提高流畅度。

### 想要实现或优化的功能

事实上并不是只有提醒卡，只是播放提醒的时候容易体现出来。所以我们并不需要拆开iwb换cpu即可轻松解决这个问题。

在播放提醒前150秒开始预加载tts语音，在播放提醒前60秒进入“专注模式”，在播放提醒前15秒开始加载水波纹动画资源（如果这个不能预加载算了），永久预加载提示音，在播放提醒前2秒置顶ci，在播放时采用多线程同时展现以上内容，并且语音保持最高优先级。播放完后关闭“专注模式”

专注模式：暂停提取主题是timer，暂停获取最新时间，暂停刷新天气，暂停自动化触发器。

努力保证播放提醒时流畅！

**Comment by LyCecilion** [comment]
不太懂 CI 的实现逻辑，但是零音总觉得，水波纹扩散动画应该是实时生成的？🤔这么说的话，「预加载」的构想，似乎就不太成立了 _(:з」∠)_

**Comment by wjj-8283** [comment]
水波纹要求不高，关键是预加载铃声（铃声老是卡住）

**Comment by wjj-8283** [comment]
其实还可以选择调用Windows原生通知接口，这个比ci流畅多了

**Comment by HelloWRC** [comment]
🤔考虑到 ClassIsland 目前的提醒架构，感觉不太容易实现在提醒前预加载这些内容，因为提醒提供方是在相应的事件（如上课、下课等）触发后会开始发出提醒，难以提前预知。不过可以考虑在提醒后把产生的内容缓存下来，以备后续使用。

**Comment by wang-lu-yuan** [comment]
建议作为低性能模式加入

**Comment by MKStoler4096** [comment]
> 🤔考虑到 ClassIsland 目前的提醒架构，感觉不太容易实现在提醒前预加载这些内容，因为提醒提供方是在相应的事件（如上课、下课等）触发后会开始发出提醒，难以提前预知。不过可以考虑在提醒后把产生的内容缓存下来，以备后续使用。

缓存下来就要考虑内存占用了👀

**Comment by liuziheng20091106** [comment]
> 🤔考虑到 ClassIsland 目前的提醒架构，感觉不太容易实现在提醒前预加载这些内容，因为提醒提供方是在相应的事件（如上课、下课等）触发后会开始发出提醒，难以提前预知。不过可以考虑在提醒后把产生的内容缓存下来，以备后续使用。

大可不必啊哥们。首先我们注意到实际上ci已经有成熟的时间偏差管理了。所以问题解决了。

启用预加载，我们可以统一额外向前偏移时间150秒，此时触发下课，但不播放下课提醒，而是开始加载，并于150秒后播放，没有逻辑问题吧?

这个最大操作的问题只是需要让所以插件的提醒都推迟，毕竟不可能每个人写插件都来一波偏移，不太现实，所以我们可以弄两个计触发器，一个预加载触发，一个正常触发。不开启预加载时两个触发器同时触发就行。（什么?触发两遍?不会的，不会有人傻到给一个函数写两个同类型触发器的。）

为什么不考虑插件呢?我们注意到ci最重要的提醒功能是上下课提醒，其它的都不重要。一般来说上下课提醒的优先级总是最高的，所以只要保持上下课提醒流畅，别的提醒都不算大事。

所谓的“缓存”也可以整上，因为大部分通知音都是水波声，没必要重复加载。触发完一批提醒后就可以移除缓存了，内存占用也不会太高。

预加载没必要钻牛角尖，只有加载一部分就行，没必要真的实现完全加载。能加载一点是一点，毕竟希沃性能就那样。

**Comment by wang-lu-yuan** [comment]
> > 🤔考虑到 ClassIsland 目前的提醒架构，感觉不太容易实现在提醒前预加载这些内容，因为提醒提供方是在相应的事件（如上课、下课等）触发后会开始发出提醒，难以提前预知。不过可以考虑在提醒后把产生的内容缓存下来，以备后续使用。
> 
> 大可不必啊哥们。首先我们注意到实际上ci已经有成熟的时间偏差管理了。所以问题解决了。
> 
> 启用预加载，我们可以统一额外向前偏移时间150秒，此时触发预备下课，不播放下课提醒，而是开始加载，并于150秒后播放，没有逻辑问题吧?（这样上下课提醒的触发器就绑定为预加载触发器，详细见下）
> 
> 这个最大操作的问题只是需要让所以插件的提醒都推迟，毕竟不可能每个人写插件都来一波偏移，不太现实，所以我们可以弄两个计触发器，一个预加载触发，一个正常触发。不开启预加载时两个触发器同时触发就行。（什么?触发两遍?不会的，不会有人傻到给一个函数写两个同类型触发器的。）
> 
> 为什么不考虑插件呢?我们注意到ci最重要的提醒功能是上下课提醒，其它的都不重要。一般来说上下课提醒的优先级总是最高的，所以只要保持上下课提醒流畅，别的提醒都不算大事。
> 
> 所谓的“缓存”也可以整上，因为大部分通知音都是水波声，没必要重复加载。触发完一批提醒后就可以移除缓存了，内存占用也不会太高。
> 
> 预加载没必要钻牛角尖，只有加载一部分就行，没必要真的实现完全加载。能加载一点是一点，毕竟希沃性能就那样。
> 
> 可以让用户选择是否启用预加载，同时也可以为每个提醒单独设置是否预加载。是和否可以分别绑定不同触发器，以实现自由定制。插件默认不启用预加载，如果插件可以提供预加载服务，那就写额外的开关（不关主程序事了）。

还是结合自动化搞比较好。for example:
_「关闭上下课提醒」复选项_行为改为_静默上下课提醒_。
- 当`<无触发器>`时，执行：
```
注册触发器：显式上下课提醒
参数：科目，任课老师，特殊提醒类型，偏移时间
详细信息：
描述=“该触发器用于触发显式上下课提醒”，对该触发器的监听器：<无>
全局监听=True
参数详细信息：
科目，类型=text
任课老师，类型=text
特殊提醒类型，类型=<可选>
偏移时间，类型=int，注释=“用于标记偏移量”
```

- 当`接收触发器：上课提醒，参数：科目=%1，任课老师=%2，特殊提醒类型=%3，显式触发=False`时，执行：`触发触发器：显式上下课提醒，参数：科目=%1，任课老师=%2，特殊提醒类型=%3，偏移量=<想要偏移的时长>`

下课提醒同理。

_「全局监听」在该构想中行为为：可接收来自所有来源的触发，欲实现这一目的，应当在应用启动时就启动监听进程。_

我知道这种实现方式太麻烦了，但是，可以顺便完善自动化缺乏的触发器（），实现更多操作，早造轮子是为了以后不现造轮子。

**Comment by liuziheng20091106** [comment]
好吧，我想的复杂了。
不是有个上课提醒吗，把上课提醒代码复制一遍，改成在上课提醒前150秒加载资源文件不得了。
下课提醒可以弄个类似的，前面那些issues也没少提准备下课提醒的事，要不顺便搓一个也行。

**Comment by FrankXiDong** [comment]
> 建议作为低性能模式加入

赞同，搞出一个低性能模式，以供低性能电脑选择使用，根据需求开启

**Comment by liuziheng20091106** [comment]
> > 建议作为低性能模式加入
> 
> 赞同，搞出一个低性能模式，以供低性能电脑选择使用，根据需求开启

那你说低性能模式单独优化什么?动画这些开关已经有了，预加载肯定不止低性能电脑用（谁希望播放提醒的时候cpu突然蹭蹭跑到100%呢）难不成做个空开关?

**Comment by HelloWRC** [comment]
截止目前，这个问题还没有产生可行的方案。我先关闭了。
