### ISSUE TITLE
升级至.NET 9.0

### ISSUE THREAD

**Issue by WHMyyds** [ClassIsland/ClassIsland#534]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=-label%3ABug) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

微软爸爸都发布了，不考律升级一下吗

### 想要实现或优化的功能

C#升级至.NET 9.0

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
不推荐，.net 8对win7的支持已经很垃圾了，再到.net 9恐怕10也会有相似的命运（）
毕竟不是每个班都能升级到11.

**Comment by FrankXiDong** [comment]
> 不推荐，.net 8对win7的支持已经很垃圾了，再到.net 9恐怕10也会有相似的命运（） 毕竟不是每个班都能升级到11.

赞同，绝大多数教室电脑都是win10，甚至有的依旧是win7。
即使是能升级到win11的，学生也不~想~敢升级啊qwq

**Comment by DryIce-cc** [comment]
开发者只需要点一下就能升级 .NET 版本，更新之后突然发现缺失 .NET 打开不了的用户要考虑的就多了.jpg

**Comment by wjj-8283** [comment]
即便是升级了，万一微软动了什么API引起bug，那也是增加开发者的负担（就像Python有的高版本不兼容有的模块），通常情况下兼容性最佳的的是最好的

**Comment by bywhite0** [comment]
这个问题就相当于抛弃Ubuntu 22.04 LTS拥抱Ubuntu 23.04一样（~~虽然Ubuntu本身就是一坨~~

**Comment by AtriDayo** [comment]
我们学校是Windows 10 20H2，升了.NET9.0会有Bug吧

**Comment by HelloWRC** [comment]
目前暂时不考虑更新 SDK 版本，但因为升级 SDK 版本之后用户还需要手动更新运行时版本，会给用户带来一些麻烦。并且 .NET 9 还不是 LTS 版本。综合上述的因素，除非新版本的 .NET SDK 出现了比较突破性的改进（比如 WPF 支持 DX11 之类的），在 1.x 阶段就不考虑升级 SDK 版本了。

**Comment by WHMyyds** [comment]
这几天学校考试没看GitHub，回复晚了
这个issue说实话我提的时候就没报很大希望，我主要是想知道开发者大佬们有没有升级的（长期）计划
但也感谢开发者们和大佬们~~在座的都是大佬啊~~的回复与指教！

**Comment by Dreamstarlake** [comment]
![Image](https://github.com/user-attachments/assets/ee5c3727-14bd-45ac-b01c-51d9767f0373)
你别说 .NET9了  .NET10都有了

**Comment by Dreamstarlake** [comment]
目前.NET10预览版为LTS版本
