### ISSUE TITLE
应用临时课表后在未更改的情况下删除对应课表会导致软件崩溃，且在重启后依旧报错。

### ISSUE THREAD

**Issue by Evereen2023** [ClassIsland/ClassIsland#542]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

希望可以切换为同一天的其它课表。

### 实际结果

重复爆出各种错误（看着像数据库与天气相关的）。

### 重现步骤

1.先向ClassIsland添加两个同天课表
2.将其中一个作为临时课表
3.删除对应课表
4.重启，可以看到重复崩溃

### 堆栈跟踪（可选）

```shell
由于是在班级电脑上出现的错误，并未记录相关报错。
```

### 应用版本

15..0.4

### 操作系统版本

Windows 10（具体版本未知）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
测试一下 #535 ？

**Comment by DryIce-cc** [comment]
@Evereen2023
您描述的问题应该是我编写的“标记换课课程”部分的代码问题所致，已在测试通道中进行修复，对所有造成不便的用户深表歉意。
您可以在 应用设置-更新-更新设置 中，将「更新通道」修改为「测试通道」，然后更新到最新的测试版本 ![](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&label=) 再次测试吗？

**Comment by Evereen2023** [comment]
好的好的，周一我去学校测试一下。等我回复。
同时，在此感谢你们做出来了这么好的软件供大家使用！

**Comment by Evereen2023** [comment]
没有问题了，感谢！
