### ISSUE TITLE
组件请求区

### ISSUE THREAD

**Issue by penglin2024** [ClassIsland/ClassIsland#544]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=-label%3ABug) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

感觉在qq群里面求别人编写一个插件效率不是特别高，而issue里面并不支持提出能用插件解决的请求

### 想要实现或优化的功能

增加插件请求板块来集中收集用户关于插件的需求

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by bywhite0** [comment]
Issues 主要是用来汇报 ClassIsland 本体相关问题的，感觉放在 Discussion 更合适

**Comment by penglin2024** [comment]
抱歉，可能是我的表述出了问题
本来也没有想放到issue里面
但是感觉discuss里面没多少人看
我想的是在官网或者QQ群里面做好引流或者单独开个小板块

**Comment by HelloWRC** [comment]
我觉得在 Discussion 里开一个板块来收集插件请求，然后在开发文档等地方引流过来可能会比较好

**Comment by penglin2024** [comment]
我感觉也挺好（discuss主要是没人翻看，能像投票一样做好引流就好了）

**Comment by HelloWRC** [comment]
已完成。添加了[插件功能请求](https://github.com/ClassIsland/ClassIsland/discussions/categories/%E6%8F%92%E4%BB%B6%E5%8A%9F%E8%83%BD%E8%AF%B7%E6%B1%82)板块，并且在文档和 Issues 提交区中做了相应的引流。
