### ISSUE TITLE
主界面部件颜色单独设置

### ISSUE THREAD

**Issue by ApleG** [ClassIsland/ClassIsland#546]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=-label%3ABug) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

主题色为防止开关控件颜色过淡而看不清，会自动调整对比度，而主界面的进度条、上课提醒时显示的底色、上课结束倒计时底色等跟随了主题色，导致其相比调色板中预览的颜色偏深，无法实现用户根据sRGB值精确调整此些部件颜色的目的（想调成初音色，结果发现偏深绿色...）
![7a9223e430a3ad3f](https://github.com/user-attachments/assets/0f53171b-33aa-4ee1-b7c6-2a28f83f6341)

### 想要实现或优化的功能

希望可以加入单独设置主界面（进度条、上课提醒时显示的底色、上课结束倒计时底色等）颜色的功能（就像字体颜色一样可以覆盖主题默认值）

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by DryIce-cc** [comment]
应该和 #440 差不多？感觉可以合并

**Comment by HelloWRC** [comment]
> 应该和 #440 差不多？感觉可以合并

那就合并过去吧
