### ISSUE TITLE
1.5.2.2 更新后会导致部分字体省略号错位

### ISSUE THREAD

**Issue by tudouneeyee** [ClassIsland/ClassIsland#566]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

省略号归位

### 实际结果

1.5.2.2更新后会导致部分字体省略号错位

### 重现步骤

先切换部分字体
用文本打出省略号
观察结果
![屏幕截图 2024-12-16 091216](https://github.com/user-attachments/assets/49cb4326-b390-40e4-bf09-a3c4d99026b2)
![屏幕截图 2024-12-16 100402](https://github.com/user-attachments/assets/da3a3a0b-4342-4267-9d8d-a6c5a1287118)
![屏幕截图 2024-12-16 091216](https://github.com/user-attachments/assets/44ae181e-d1ca-4d95-b544-ff1f3a73e961)
![屏幕截图 2024-12-16 100415](https://github.com/user-attachments/assets/e940a01b-3fec-46d7-b08c-32ac9e241af2)
![屏幕截图 2024-12-16 100402](https://github.com/user-attachments/assets/b7ebd6a2-f36c-4e51-9b6c-ebee0314f4f8)
![屏幕截图 2024-12-16 100415](https://github.com/user-attachments/assets/a202c90b-0da7-4a59-9fc0-e3aef6b8e7de)

### 应用版本

1.5.2.2

### 操作系统版本

Dev 26120.2510

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
不是错位，这是字体本身的设置，与ClassIsland无关

检查一下你的字体！

**Comment by bywhite0** [comment]
建议使用旧版本测试并截图注明版本号，你这样并不能证明是新版本导致的问题

**Comment by tudouneeyee** [comment]
> 建议使用旧版本测试并截图注明版本号，你这样并不能证明是新版本导致的问题

有道理

**Comment by tudouneeyee** [comment]
> 不是错位，这是字体本身的设置，与ClassIsland无关
> 
> 检查一下你的字体！
> 
> 以及，用 Word 打出来这几种字体，应该也是这个效果。您看看是不是。

不是,之前均正常

**Comment by tudouneeyee** [comment]
> ### 检查清单
> * [x]  我已更新到最新版 ![最新的版本号](https://camo.githubusercontent.com/2a836f73bed1b322d58df09866ea8ae3238ee95e9361b55a443b62ea898e286a/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f762f72656c656173652f436c61737349736c616e642f436c61737349736c616e643f696e636c7564655f70726572656c6561736573267374796c653d666c61742d737175617265266c6162656c3d) 或 ![最新的版本号](https://camo.githubusercontent.com/33d7cd6d3a1d13ac92db4ffd3f2806a556dd20b393cafa5bde5341b4b46c73b2/68747470733a2f2f696d672e736869656c64732e696f2f6769746875622f762f72656c656173652f436c61737349736c616e642f436c61737349736c616e643f7374796c653d666c61742d737175617265266c6162656c3d) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
> * [x]  我已在 [议题](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
> * [x]  我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。
> 
> ### 期望的行为
> 省略号归位
> 
> ### 实际结果
> 1.5.2.2更新后会导致部分字体省略号错位
> 
> ### 重现步骤
> 先切换部分字体 用文本打出省略号 观察结果 ![屏幕截图 2024-12-16 091216](https://private-user-images.githubusercontent.com/185571387/395935791-49cb4326-b390-40e4-bf09-a3c4d99026b2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDAyMDAsIm5iZiI6MTczNDMzOTkwMCwicGF0aCI6Ii8xODU1NzEzODcvMzk1OTM1NzkxLTQ5Y2I0MzI2LWIzOTAtNDBlNC1iZjA5LWEzYzRkOTkwMjZiMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwOTA1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZDRmMjI5ZDJhOTIyNzk4MTJkZGQ2NjZmOTRkZTY1MWUxNzNmMjljZjFlM2E1YTI0YmY1NTg2YTA5NzMzNzYwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.mGso7gQ9SbXK1z83SDL_C9c2tpyYZ_ZmgbCnpg82C2M) ![屏幕截图 2024-12-16 100402](https://private-user-images.githubusercontent.com/185571387/395935810-da3a3a0b-4342-4267-9d8d-a6c5a1287118.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDAyMDAsIm5iZiI6MTczNDMzOTkwMCwicGF0aCI6Ii8xODU1NzEzODcvMzk1OTM1ODEwLWRhM2EzYTBiLTQzNDItNDI2Ny05ZDhkLWE2YzVhMTI4NzExOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwOTA1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wM2IwNjZkYzUyOWJhZmIzYmRjMThiMDFiYjQ2YzViNjM5OTQyODVkZmZkYjNiNGExNDk1ZjE1NWExZThmZjlhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.zsMqIBsES3oHp1ssxgTk8keQs82Oteb339jwqfhercc) ![屏幕截图 2024-12-16 091216](https://private-user-images.githubusercontent.com/185571387/395935850-44ae181e-d1ca-4d95-b544-ff1f3a73e961.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDAyMDAsIm5iZiI6MTczNDMzOTkwMCwicGF0aCI6Ii8xODU1NzEzODcvMzk1OTM1ODUwLTQ0YWUxODFlLWQxY2EtNGQ5NS1iNTQ0LWZmMWYzYTczZTk2MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwOTA1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00NjNiYmZiMGU5M2RjOWQxZDFmNWVmODU1OWVkOWIwMGNhMjI2OGFlMzRjYTMxYWNhNGQwZGRkYjAxZTA2NjIwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vPecsEd3p5Wos9aK8w2g8uR--ZFZsguru4om3y38iyc) ![屏幕截图 2024-12-16 100415](https://private-user-images.githubusercontent.com/185571387/395935880-e940a01b-3fec-46d7-b08c-32ac9e241af2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDAyMDAsIm5iZiI6MTczNDMzOTkwMCwicGF0aCI6Ii8xODU1NzEzODcvMzk1OTM1ODgwLWU5NDBhMDFiLTNmZWMtNDZkNy1iMDhjLTMyYWM5ZTI0MWFmMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwOTA1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWE1YWNiMzRiYzFmMWU4NjI5OThjM2M4OGUyNGU5MzFlY2I3MmU0ZmEzNDcyZDU3YmRmZmFlMDZlNTUwNzI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.P5WcDBCKx2cEXfB4xOy82cG5zSnasFDpIYISswwsDqs) ![屏幕截图 2024-12-16 100402](https://private-user-images.githubusercontent.com/185571387/395935892-b7ebd6a2-f36c-4e51-9b6c-ebee0314f4f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDAyMDAsIm5iZiI6MTczNDMzOTkwMCwicGF0aCI6Ii8xODU1NzEzODcvMzk1OTM1ODkyLWI3ZWJkNmEyLWYzNmMtNGU1MS05YjZjLWViZWUwMzE0ZjRmOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwOTA1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zYTM1ZGJjOWYyYmZjZDdkNzQ0MWUzNjFjNjQxZmFiZjEwNzQ1NzU1ZjY4N2I0MjM5NzA0NTkwZDAyOTg1MjBkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.L2zWJ2VvRh_nntHaz-3ggXY_ygXoICPsKNQOv7NOWd4) ![屏幕截图 2024-12-16 100415](https://private-user-images.githubusercontent.com/185571387/395935920-a202c90b-0da7-4a59-9fc0-e3aef6b8e7de.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzNDAyMDAsIm5iZiI6MTczNDMzOTkwMCwicGF0aCI6Ii8xODU1NzEzODcvMzk1OTM1OTIwLWEyMDJjOTBiLTBkYTctNGE1OS05ZmMwLWUzYWVmNmI4ZTdkZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMjE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTIxNlQwOTA1MDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kNzFlOThjZTViOGY5M2NlMzY2OTVkMDg2YjU2ZjcxNWJmYzkwNjRhNTQxMzdlYzdjNGJiYzA4ZWY3N2RkM2FiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.-eo5OdbIBRrKv8NvtPCmLFIm7G2YkO8zlZqWgdEy22E)
> 
> ### 堆栈跟踪（可选）
> _No response_
> 
> ### 应用版本
> 1.5.2.2
> 
> ### 操作系统版本
> Dev 26120.2510
> 
> ### 最后一步
> * [x]  我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。
