### ISSUE TITLE
改进集控功能

### ISSUE THREAD

**Issue by hjx2289206** [ClassIsland/ClassIsland#576]
### 检查清单

- [X] 我已将本应用更新到最新测试版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=)，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认我想要的功能还没有实现。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=-label%3ABug) 和 [ClassIsland 文档](https://docs.classisland.tech/app/)中检索，确认我想要的功能未被提交过。
- [X] 我认为我想要的功能是用户广泛需要的，插件不能替代的，且没有超出 ClassIsland 作为**灵动课表**的开发目标，而非添加与课表及教学辅助无关的内容。（您可以学习[编写插件](https://docs.classisland.tech/dev/plugins/create-project)来实现特殊的需求）。
- [X] 我已知晓由于开发者时间精力有限，加上已经积压了大量的功能请求，我提交的功能请求可能需要比较久的时间才能实现。

### 背景与动机

集控功能现在还停留在刚出的那一块，老师/电教可不一定会弄

### 想要实现或优化的功能

1.可部署在私有服务器上
2.有一个更清晰可供编辑的网站前端界面，方便远程操作换课，改课表
3.也许可以添加一些通知界面，方便老师直接在办公室发布一些通知
4.也许也可以加上作业通知界面

### 最后一步

- [X] 我认为上述的描述已经足以详细，以便开发人员理解您想要的功能。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by bywhite0** [comment]
已经在做了

https://github.com/ClassIsland/ManagementServer

**Comment by HelloWRC** [comment]
这些目前已经是集控服务器的开发目标了。如果您还想给集控服务器提出建议，请在集控服务器的仓库里开启工单。
