### ISSUE TITLE
在安装ExtraIsland后添加“更好的倒计时”，出现排版错版

### ISSUE THREAD

**Issue by Windows-Edge** [ClassIsland/ClassIsland#577]
### 检查清单

- [X] 我已更新到最新版 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?include_prereleases&style=flat-square&label=) 或 ![最新的版本号](https://img.shields.io/github/v/release/ClassIsland/ClassIsland?style=flat-square&label=) 测试，并看过[最新提交](https://github.com/ClassIsland/ClassIsland/commits/dev/)，确认这一 Bug 还没有修复。
- [X] 我已在 [Issues](https://github.com/ClassIsland/ClassIsland/issues?q=label%3ABug) 中检索，确认这一 Bug 未被提交过，并且在[常见问题](https://docs.classisland.tech/app/faq/faq.html)中没有解决方案。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题（关于其他非程序本身的问题应当在 Discussion 板块提出）。

### 期望的行为

正常显示

### 实际结果

如图所示，在安装ExtraIsland后添加“更好的倒计时”，出现如图所示的现象
![image](https://github.com/user-attachments/assets/b0e30348-4528-4e12-890e-cc11d478e36c)

### 重现步骤

1.安装ExtraIsland
2.添加“更好的倒计时”

### 应用版本

1.5.2.2

### 操作系统版本

win10 22h2，操作系统内部版本19045.4291

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题。如果我的 issue 没有按照上述的要求填写，可能会被无条件关闭。

**Comment by MKStoler4096** [comment]
这是因为设定宽度后选择了压缩对齐

**Comment by WHMyyds** [comment]
这个你不该找插件开发者反馈问题吗（）

**Comment by HelloWRC** [comment]
这个应该不属于 ClassIsland 本体的问题，请先去插件那里提工单。

**Comment by LiPolymer** [comment]
本问题已在ExtraIsland仓库被打开☝🤓
https://github.com/LiPolymer/ExtraIsland/issues/5
@HelloWRC 请关闭这个议题🤤🙏
