### ISSUE TITLE
允许自定义课间名称

### ISSUE THREAD

**Issue by meiyoushuru** [ClassIsland/ClassIsland#63]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

当前版本中，课间只能在时间表中设定长度，无法通过名称区分和显示普通课间、大课间、午休等，而将其设置为上课也并不合理（例如我设置了上课时隐藏，设置大课间为上课会导致大课间时无法看到顶栏）

### 想要实现或优化的功能

在时间表中添加课间时，允许用户对其进行命名

**Comment by HelloWRC** [comment]
感谢您的建议。

**Comment by HelloWRC** [comment]
已实现。
