### ISSUE TITLE
[功能请求]: 希望可以修改某些文本使其可以自定义

### ISSUE THREAD

**Issue by kaokao221** [ClassIsland/ClassIsland#69]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

考虑到不同情况的适用性

### 想要实现或优化的功能

![image](https://github.com/HelloWRC/ClassIsland/assets/88539021/0eec44d1-8903-47e6-8fcb-3de5f62871f2)
希望能够修改如图的即将上课四个字，适应不同的场景，例如 #68 中的，在两堂连续作业考试化中改为“作业即将结束”，与之对应
![image](https://github.com/HelloWRC/ClassIsland/assets/88539021/974b0806-5f26-4007-9612-87d183f7911a)
这里的“距离上课”可以改为“该科结束”等等，后面的下一节可以改为下一科一类

**Comment by HelloWRC** [comment]
感谢您的建议，不过这个功能可能有点超出ClassIsland的开发目标了。未来可能会通过扩展的方式实现这个功能。

**Comment by HelloWRC** [comment]
已实现。
