### ISSUE TITLE
[功能请求]: TTS可以选择播放情景

### ISSUE THREAD

**Issue by jiangyin14** [ClassIsland/ClassIsland#71]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

年级主任要求的（）

### 想要实现或优化的功能

在提醒选项卡的TTS选项下，可以通过复选框的勾选，决定是否在特定事件类型播放语音

**Comment by HelloWRC** [comment]
此功能已经实现。
