### ISSUE TITLE
测试版无法更新

### ISSUE THREAD

**Issue by meiyoushuru** [ClassIsland/ClassIsland#74]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我的问题没有得到解答。
- [X] 我已确认我要反馈的问题还没有在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支上修复。
- [X] 我已知晓并同意，此处仅用于汇报程序中存在的问题。若这个 Issue 是关于其他非程序本身问题，则我的 Issue 可能会被无条件自动关闭或/并锁定。（这些问题应当在 Discussion 板块提出。）

### 重现步骤

我尝试将测试版1.3.2.0更新至1.3.3.0

### 期望的行为

应该正常完成更新，但是并没有。

### 实际结果

更新下载速度十分缓慢（几k/s），且会在后段卡住并中断，无法完成更新
![IMG_0567](https://github.com/HelloWRC/ClassIsland/assets/153412047/416bda3d-a02a-4d5d-926e-506a007289a9)
梯子挂或不挂、全局与否都已尝试，都无法完成更新网页是可以正常访问的，应该不是网络问题。

若暂时无法解决或是网络问题，是否可以告诉我该如何在Github上直接下载最新版本，应该替换哪些文件以使得设置和档案得到保留。

### 应用版本

1.3.2.0

### 操作系统版本

Windows 11 23H2

### 最后一步

- [X] 我认为上述的描述已经足以详细，以允许开发人员能复现该问题

**Comment by jiangyin-srinternet** [comment]
请在更新页面下滑尝试选择App Center下载源，通常该源下载速度最快。（我校能达到4mb/s）

**Comment by HelloWRC** [comment]
三个镜像源都试试看

**Comment by HelloWRC** [comment]
如果是从GitHub手动更新的话，直接替换`ClassIsland.exe`就可以了

**Comment by meiyoushuru** [comment]
> 如果是从GitHub手动更新的话，直接替换`ClassIsland.exe`就可以了

好的，了解了，谢谢！

**Comment by Doctor-yoi** [comment]
建议尝试从github手动下载后对主程序进行替换
