### ISSUE TITLE
课表里的字体的大小与颜色

### ISSUE THREAD

**Issue by jizilin6732** [ClassIsland/ClassIsland#80]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

在学校里。后排的同学反馈字体太小了有一点看不清，在前排的我总觉得颜色不够显眼

### 想要实现或优化的功能

1. 添加修改字体选项
2. 添加修改课表文字颜色的选项

**Comment by meiyoushuru** [comment]
> ### 检查清单
> * [x]  我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
> * [x]  我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
> * [x]  我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。
> 
> ### 背景与动机
> 在学校里。后排的同学反馈字体太小了有一点看不清，在前排的我总觉得颜色不够显眼
> 
> ### 想要实现或优化的功能
> 1. 添加修改字体选项
> 2. 添加修改课表文字颜色的选项

字体是可以修改的，我没记错的话是在`应用设置-外观`中。你可以考虑增大`缩放`，降低`透明度`，或者（以及）选择更重的`字重`。如果你需要修改字体，也提供了修改字体的选项，在同一选项卡中。
课表颜色目前确实无法更改，可以让作者增加该选项。（不过我觉得还是白色比较好看

**Comment by jiangyin-srinternet** [comment]
字重选择Heavy也许能解决

**Comment by LiuYan-xwx** [comment]
跟wrc自己提的 #26 有点类似

**Comment by HelloWRC** [comment]
已修复。

**Comment by HelloWRC** [comment]
> 已修复。

点错了

**Comment by HelloWRC** [comment]
已实现。
