### ISSUE TITLE
课表圆角

### ISSUE THREAD

**Issue by jizilin6732** [ClassIsland/ClassIsland#81]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

怎么说呢，就觉得方方正正的不好看，想改一下课表的圆角
![image](https://github.com/HelloWRC/ClassIsland/assets/162853646/febaab34-4079-4848-a50d-e37f0613bc75)
![image](https://github.com/HelloWRC/ClassIsland/assets/162853646/3245f839-2611-4de2-a7e5-00d72f68bcdb)

### 想要实现或优化的功能

1. 添加圆角修改选项
2. 添加提醒横幅修改圆角选项

**Comment by jiangyin-srinternet** [comment]
顶 @HelloWRC

**Comment by meiyoushuru** [comment]
同求。圆角与Win 11的系统风格更加符合。

**Comment by HelloWRC** [comment]
感谢您的建议。

**Comment by jiangyin14** [comment]
课表圆角最好提示也能圆角，和水波纹强调提示效果统一

**Comment by HelloWRC** [comment]
已实现。
