### ISSUE TITLE
[功能请求]: 改进鼠标悬停淡化课程表功能

### ISSUE THREAD

**Issue by Misaka2298** [ClassIsland/ClassIsland#82]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

学校电脑大多数应该都是触屏（至少我呆过的两个省份的电脑是这样） ，而按照现有的”鼠标只要停留在课表上课表就会一直淡化“逻辑很容易出现在单击操作且单击位置在课表上之后尽管没有对电脑进行任何操作，课表仍然淡化的情况
草我说的好绕，反正就是感觉现在的淡化逻辑不适合触屏的电脑，比如我班今天在电脑附近的一个同学关闭了 关闭按钮跟课表重合的文件夹 之后课表一直隐藏的现象，老师在讲台坐着我也没法去点下屏幕只能干着急，老急人了

### 想要实现或优化的功能

在设置界面增加一个切换淡化逻辑的项，我大概想了几个模式
1.现有的鼠标只要停留在课表上课表就会一直淡化
2.鼠标停留在课表上仍然淡化，但如果在课表上停留n秒一直没有移动的话就会重新显示
3.无视鼠标，不淡化

**Comment by meiyoushuru** [comment]
考虑到放PPT时临时需要淡化课表以显示出被课表遮挡的内容，鼠标悬停后保持淡化的逻辑是没有问题的。
Windows对触摸点按和鼠标点按的feedback是不一样的，因此可以考虑对光标的点按和移动来源作区分，如果是触摸来源就延时后取消淡化，如果是鼠标来源就保持淡化。
另外，我建议是不管是鼠标悬停还是触摸后的淡化选项都应该在设置中给出可选项，以供选择。

**Comment by jiangyin-srinternet** [comment]
设置中可以设置前台应用全屏时隐藏课表，可考虑基于该功能改进

**Comment by jizilin6732** [comment]
点击超过3次，提示是否永久隐藏（可在托盘再显示）

**Comment by HelloWRC** [comment]
不过因为 ClassIsland 主窗口被设置了 `WS_EX_TRANSPARENT` 样式，主窗口无法对鼠标或触摸输入事件做出任何响应，因此在目前的实现中，是通过轮询鼠标光标的位置来判断鼠标是否移入界面的。而且在一些情况下，因为触摸事件不会移动鼠标指针，这种轮询方式就会导致即使点击了界面以外的区域，ClassIsland 依然保持淡化的情况。

目前正在考虑寻找更好的判断方式，支持对触摸和鼠标输入做出不同选择。

**Comment by jiangyin14** [comment]
> 不过因为 ClassIsland 主窗口被设置了 `WS_EX_TRANSPARENT` 样式，主窗口无法捕获鼠标或触摸输入事件，因此在目前的实现中，是通过轮询鼠标光标的位置来判断鼠标是否移入界面的。而且在一些情况下，因为触摸事件不会移动鼠标指针，这种轮询方式就会导致即使点击了界面以外的区域，ClassIsland 依然保持淡化的情况。
> 
> 目前正在考虑寻找更好的判断方式，支持对触摸和鼠标输入做出不同选择。

比如对于其他WPF构建的页面进行``` 滑动 ```操作时，并不移动光标，于是课表保持淡化

**Comment by HelloWRC** [comment]
目前可以使用 RawInput 来直接对触摸输入做出响应，并区分鼠标输入与触摸输入。

**Comment by HelloWRC** [comment]
已实现。
