### ISSUE TITLE
[功能请求]: 提醒音量调节

### ISSUE THREAD

**Issue by jizilin6732** [ClassIsland/ClassIsland#89]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

在上下课的时候，没有单独的调节音量，导致老师或同学会被吓到（包括我）

### 想要实现或优化的功能

添加提醒音效调节滑块

**Comment by jiangyin14** [comment]
建议使用Windows“音量合成器”对ClassIsland主程序音量进行调节

**Comment by jizilin6732** [comment]
> 建议使用Windows“音量合成器”对ClassIsland主程序音量进行调节

好像调完后整个程序的声音都小了

**Comment by HelloWRC** [comment]
> 建议使用Windows“音量合成器”对ClassIsland主程序音量进行调节

这个不太方便，会影响到整个程序的声音

**Comment by jiangyin14** [comment]
感谢 这个功能还是比较需要的

**Comment by HelloWRC** [comment]
已实现。
