### ISSUE TITLE
[功能请求]: 希望添加更多复杂的隐藏窗口条件

### ISSUE THREAD

**Issue by rayrenxiang** [ClassIsland/ClassIsland#96]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

若在上课时设置了隐藏窗口。课程为大课间、早读等时段会触发窗口隐藏导致无法看见顶栏。
故希望添加更为复杂的条件 这或许可以解决issue#63的问题

### 想要实现或优化的功能

![image](https://github.com/HelloWRC/ClassIsland/assets/95950587/06aa2dae-4bc7-4efe-b447-5a53e925805a)
比如：在上课时且在前台是最大化窗口时隐藏

**Comment by HelloWRC** [comment]
感谢您的建议

**Comment by Misaka2298** [comment]
也建议添加一个“当某应用最大化时”的条件，如果能实现的话

**Comment by gaopx11233** [comment]
其实也可以加一个“上课且正在使用全屏或最大化应用”的条件

**Comment by DryIce-cc** [comment]
看起来已在 74f71803a2fdaf22494721641289687c0282f0bd 实现，允许添加更为复杂的条件。
目前还没有发布，您可以在 Actions 中下载体验。
