### ISSUE TITLE
[功能请求]: 增加每日看板界面

### ISSUE THREAD

**Issue by meiyoushuru** [ClassIsland/ClassIsland#97]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

目前，ClassIsland 的各类上下课提醒逻辑和机制已经相当复杂，相当多的指向对象一致而优先级不同的设置导致最终呈现的提醒效果常常与预期不符，且难以排查，也无从知晓是bug还是设置问题。

### 想要实现或优化的功能

增加一个每日看板界面，**按照时间顺序**列出以下内容：
1. 当日所有课程以及课间休息的显示，包括显示何种时间点附加信息、是否隐藏等，并指出是由用户的哪项设置直接决定的。当用户设置了冲突的选项时，应当高亮标出。
（例如，用户在时间表中将某一节课的`时间点附加信息`设置为`剩余时间`，而在课表中将该节课的`时间点附加信息`设置为`持续时间`，那么，在看板中，该节课的`时间点附加信息`应标为`持续时间`，并**高亮**标出，注明`存在冲突设置：时间表-剩余时间，课表-持续时间`）

2. 计划发出的提醒（包括倒计时等一切会使Banner产生变化的行为）的摘要（考虑到数量较多，可添加筛选功能），包括
- 发出提醒的具体时间点
- 提醒的持续时间
- 提醒的具体内容
- 提醒的形式（声音、文字等，是否为全屏）
- **提醒来源**，也就是由哪个界面的哪项设置直接决定了该提醒及其形式。当存在冲突时，应同 1 中一样高亮注明具体冲突。

这将有利于用户确定各类设置优先级并快速排查，以确保提醒按照用户预期的效果发出。

在允许的情况下，以上摘要应尽量做成可编辑的，允许用户在看板中统一快速进行临时调整和/或应用到永久设置中。

另外，在存在可能导致优先级冲突的设置选项旁，应以醒目文字提醒用户注意优先级冲突问题。

**Comment by HelloWRC** [comment]
感谢您的建议。

**Comment by jiangyin-srinternet** [comment]
👍👍👍

**Comment by HelloWRC** [comment]
已实现（1）中的功能。由于技术限制，以下功能无法实现：
 
- **（2）中计划发出的提醒**：提醒是在对应的提醒提供方接收到对应的事件（如上课、下课等）之后发布的，难以预先列出计划发出的提醒。
