### ISSUE TITLE
[功能请求]: 显示多项快速信息

### ISSUE THREAD

**Issue by LiuYan-xwx** [ClassIsland/ClassIsland#98]
### 检查清单

- [X] 我已经在 [Issues](https://github.com/HelloWRC/ClassIsland/issues?q=) 中找过我要提出的问题，没有找到相同问题的ISSUE。
- [X] 我已经详细阅读过应用的帮助文档，但我想要的功能没有实现。
- [X] 我已确认我的功能尚未在 [dev](https://github.com/HelloWRC/ClassIsland/commits/dev/) 分支实现。

### 背景与动机

可以同时看到多种信息

### 想要实现或优化的功能

在快速信息处(课表左边那块)可以显示多项内容，比如时间和天气一起显示

**Comment by HelloWRC** [comment]
> 或许考虑轮播？ @HelloWRC

轮播感觉太有限了，我觉得可以弄成像kde面板那样可以自定义要显示的组件（比如课表、时间、天气等等）的形式。

**Comment by HelloWRC** [comment]
已在dev实现。
